### ISSUE TITLE
admin\includes\languages\english.php

### ISSUE THREAD

**Issue by Tomasonx** [gburton/Responsive-osCommerce#168]
admin\includes\languages\english.php 

must be (!?) close

on last line ?>

**Comment by gburton** [comment]
No.

**Comment by Tomasonx** [comment]
OK.
Why?

**Comment by newburns** [comment]
Lol. Why does it need to be close

**Comment by Tomasonx** [comment]
This is your answer...

**Comment by gburton** [comment]
For files that contain only PHP code, the closing tag ("?>") is **never permitted**. It is **not required** by PHP, and omitting it prevents the accidental injection of trailing white space into the response.

**Comment by Tomasonx** [comment]
Thank you
