### ISSUE TITLE
ht_noscript module

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/Responsive-osCommerce#181]
Outputs body text (div) in the head, which fails html validation.

Would it be better as a header content module?

**Comment by BrockleyJohn** [comment]
Bizarrely, having cleared other errors, it's stopped whingeing about that one... but before it didn't like a div in the header

**Comment by gburton** [comment]
I think it would be better as a content module.  I'll put it onto the "to do" list.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/pull/237
