### ISSUE TITLE
/index.php?cPath=0

### ISSUE THREAD

**Issue by CmdLnInt** [gburton/Responsive-osCommerce#193]
Showing the entire catalogue looks strange although I believe it is displayed correctly?

**Comment by gburton** [comment]
What is the issue ?

**Comment by CmdLnInt** [comment]
Was initially an aesthetic observation which you should ignore, however I
do see a real issue in this view. I have 36 categories, but there seem to
be random gaps in the grid layout.



Davin Menhinick
082 874 4391

**Comment by gburton** [comment]
cPath=0 would never be used.  There is no link to it from anywhere in osCommerce.

**Comment by CmdLnInt** [comment]
Its not normally used however I believe I am one of many who like to have the full category list on the front page. Google "Oscommerce categories on home page" and you will see what I mean.

**Comment by gburton** [comment]
Using cPath=0 is not the correct way to do this.
