### ISSUE TITLE
TypeError in ht_product_colorbox.php

### ISSUE THREAD

**Issue by crazy-colorado** [gburton/Responsive-osCommerce#210]
includes/modules/header_tags/ht_product_colorbox.php : line 49

When viewing a product with only one image using Firefox or Chrome, this line produces a "TypeError: Cannot read property 'substring' of undefined" error in the console.  This is due to the following portion of line 49.

var imgid = $(this).attr(\'id\').substring(9);

Surrounding this with an if statement to check if variable exists removes the error.

**Comment by gburton** [comment]
Please supply (tested) code - thanks!

**Comment by crazy-colorado** [comment]
Resolved with pull request #221 from gadlol/patch-13 

var imgid = $(this).attr(\'id\') ? $(this).attr(\'id\').substring(9) : 0;
