### ISSUE TITLE
Misbehaved Buy Now Button in Product Listing Page

### ISSUE THREAD

**Issue by Moxamint** [gburton/Responsive-osCommerce#224]
The system kicked me to the home page after clicking on "Buy Now" button in the product listing page.  Item was added properly.  "Display Cart After Adding Product" was set to "false" in admin.

**Comment by gburton** [comment]
Confirmed bug in Responsive.  

Can someone test in "normal" oscommerce;

1.  Set "Display Cart After Adding Product" to true
Go to category page, click "buy now" on a product (that has no attributes).  
Cart redirects to shopping_cart, with product added to cart.
All is well.

2.  Set "Display Cart After Adding Product" to false
Go to category page, click "buy now" on a product (that has no attributes).  
Cart redirects to index, with product added to cart.

Problem:  functionality should return to the category page the product was added from.

If the problem exists in "normal" osCommerce, it needs to be looked at for 2.3.5
If the problem does not exist in "normal", then it needs to be looked at asap

Thanks

**Comment by Kymation** [comment]
Tested in osCommerce 2.3.4 stock and Gold. Both work as expected.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/pull/246

**Comment by Moxamint** [comment]
Thanks Gary.  #246 has fixed this issue I reported for my site.

**Comment by skleiner** [comment]
With "Display Cart After Adding Product" was set to "false" in admin.

Before update, went to index after buy now.

.After update, to category of item chosen.

**Comment by mikepo** [comment]
confirmed, after update, cart is updated, and now remains in the category listing.

**Comment by gburton** [comment]
Thank You @Moxamint @skleiner @mikepo 

https://github.com/gburton/Responsive-osCommerce/commit/8e672d6c4eeaffde68ca09e6496a4330ba2c7159
