### ISSUE TITLE
jquery async problem

### ISSUE THREAD

**Issue by gadlol** [gburton/Responsive-osCommerce#227]
There is a bug that appears SOMETIMES because there is the async :

<script src="ext/jquery/jquery-1.11.1.min.js" async></script>

have a look at the screenshot:

![screenshot from 2015-10-12 21 17 30](https://cloud.githubusercontent.com/assets/518451/10435229/528561ba-7127-11e5-8d85-904f3de2bddc.png)

NOTE: tested only locally

But if I refresh the page then its ok.

I repeat that happens sometimes.

![screenshot from 2015-10-12 21 25 49](https://cloud.githubusercontent.com/assets/518451/10435321/f04d872e-7127-11e5-8103-437420d6e931.png)

**Comment by BrockleyJohn** [comment]
Join the party here: http://forums.oscommerce.com/topic/408272-bugs-in-edge-version-of-234-responsive/

**Comment by gburton** [comment]
Easiest option:  remove the async tag.

**Comment by jwisdom** [comment]
Why not load jquery in template bottom right before bootsrap?  I have it running that way and so far I'm not aware of any problems.  Have you found a reason not to do this?

**Comment by gburton** [comment]
We were doing this, and it caused lots of problems.  So it was moved back to template_top

**Comment by jwisdom** [comment]
I see.  In hind sight I realized I've moved anything requiring jQuery into my footer loading after it and bootstrap.

**Comment by crazy-colorado** [comment]
I did move jquery to load before bootstrap.js and footer-scripts in template.bottom.php.  Also had to change the execution group for a few modules from header-tags to footer-scripts.  Have not had any issues with functionality or errors.

**Comment by gburton** [comment]
async removed

https://github.com/gburton/Responsive-osCommerce/commit/6eb71b3b9cfa48877a6d22a7944c1ab23e8aab56
