### ISSUE TITLE
address_book_details module

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#243]
https://github.com/gburton/Responsive-osCommerce/blob/master/includes/modules/address_book_details.php#L163

We have an extra parameter "0"

    'country', 
    (isset($entry['entry_country_id']) ? $entry['entry_country_id'] : STORE_COUNTRY), 
    0,
    'required aria-required="true" aria-describedby="atCountry" id="inputCountry"'

How I believe it should be:

    'country', 
    (isset($entry['entry_country_id']) ? $entry['entry_country_id'] : 0), 
    'required aria-required="true" aria-describedby="atCountry" id="inputCountry"'

Will look at older 234 and update issue appropriately.

**Comment by gburton** [comment]
234 does not suffer the same issue, so this bug must have been introduced at the update to Responsive Forms.

**Comment by skleiner** [comment]
Testing this with 
create_account.php
and
address_book_process.php in New Address Book Entry
All's good from what I see.

**Comment by gburton** [comment]
Thanks for testing @skleiner Steve - I will do a few more tests and commit to core.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/commit/5efc41bdf21660bb4244dc5de54de2dc8bd48acf
