### ISSUE TITLE
Clean Up Language Files

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#247]
Particularly /includes/languages/english.php

In here there are constants that are unused (hence should be removed entirely)
Also constants that are not used site-wide (hence should be moved to the relevant language sub-file)

**Comment by Piernas** [comment]
I'm in process of cleaning up english.php... What a load of useless stuff is in there!!!!
I found some strings used only inside classes. Is is a good idea to load those strings from inside the class instead of the page that uses the class?

**Comment by gburton** [comment]
When you say "classes" do you mean "modules" ?

**Comment by Piernas** [comment]
No, I mean classes, ie. define('JS_ERROR_NO_PAYMENT_MODULE_SELECTED', '* Please select a payment method for your order.\n');

**Comment by gburton** [comment]
As an example, that one would need to be available in checkout_payment.
You do what you think is correct, and test it.  If it all works, push it.

**Comment by Piernas** [comment]
Do you know what's the use of JQUERY_DATEPICKER_I18N_CODE?
Seems like it's not implemented

**Comment by Piernas** [comment]
english.php done. Moved a lot of text to their corresponding files and removed 38 orphan strings. I'm still in doubt JQUERY_DATEPICKER_I18N_CODE but I'm pretty sure it is not curently in use.

Will test everything and commit changes.

**Comment by newburns** [comment]
@Piernas 
Were you able to submit those changes? I was going to tackle the orphaned strings, but didn't want to do double work

**Comment by Piernas** [comment]
@newburns here you have it, but it's probably outdated as some lanuage files has changed since then.
https://github.com/gburton/Responsive-osCommerce/pull/278/commits/212282ad83c2fc0f9a81564863cbfc1dd3a07180
