### ISSUE TITLE
checkout_new_address.php: wrong number of parameters tep_get_country_list()

### ISSUE THREAD

**Issue by katapofatico** [gburton/Responsive-osCommerce#249]
[On line 157](https://github.com/gburton/Responsive-osCommerce/blob/master/includes/modules/checkout_new_address.php#L157) we can see tep_get_country_list() calling with 4 parameters:

`echo tep_get_country_list('country', STORE_COUNTRY, 0, 'id="inputCountry" aria-describedby="atCountry"');`

However, [tep_get_country_list() declaration](https://github.com/gburton/Responsive-osCommerce/blob/master/includes/functions/html_output.php#L341) defines only 3 parameters:
`function tep_get_country_list($name, $selected = '', $parameters = '')`

@gburton I have discovered this problem while searching a similar problem concerning a third party module. 

I think the solution is something like [this](https://github.com/gburton/Responsive-osCommerce/commit/49305b056647996f82563af7abc8138392a796c7#diff-65e6c4e9684da3bfbacdcd02feccdb34).

What do you think?

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/issues/243

**Comment by gburton** [comment]
Please use email for questions concerning addons, thanks.  I have updated your comment

**Comment by katapofatico** [comment]
Ok, I will do it.
However, the addon mention was only a note: the problem is independient of the mentionated addon. On #243 I see only one commit about "city" field, not solving the tep_get_country_list() calling with 4 parameters. Therefore, I thing this Issue should be reopened

**Comment by gburton** [comment]
Please read https://github.com/gburton/Responsive-osCommerce/issues/243

Comments say https://github.com/gburton/Responsive-osCommerce/commit/5efc41bdf21660bb4244dc5de54de2dc8bd48acf

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/pull/244

Ahem.  LInked you to the wrong one.  Sorry.

**Comment by katapofatico** [comment]
Ok, I referenced this code change on my first comment of this issue:

> I think the solution is something like [this](https://github.com/gburton/Responsive-osCommerce/commit/49305b056647996f82563af7abc8138392a796c7#diff-65e6c4e9684da3bfbacdcd02feccdb34).

And I insist: this change is on address_book_details.php, but I'm reffering to checkout_new_address.php

**Comment by gburton** [comment]
Please fix and push a commit.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/commit/aff8539b2e82ec5568badb0a0c78386252268c66
