### ISSUE TITLE
BUG: free shipping icon BUG on checkout_shipping.php  

### ISSUE THREAD

**Issue by katapofatico** [gburton/Responsive-osCommerce#251]
On [checkout_shipping.php#L248](https://github.com/gburton/Responsive-osCommerce/blob/master/checkout_shipping.php#L248) we can see an array access:
```php
<div class="panel-heading"><strong><?php echo FREE_SHIPPING_TITLE; ?></strong>&nbsp;<?php echo $quotes[$i]['icon']; ?></div>
```
There's not any array lopping with $i, therefore it throws:
`Notice: Undefined offset: 95 in Unknown on line 0`

I think it's a copy&paste error, copied from [few lines down](https://github.com/gburton/Responsive-osCommerce/blob/master/checkout_shipping.php#L256):

```php
} else {  // (IF IT'S NOT FREE SHIPPING)
      for ($i=0, $n=sizeof($quotes); $i<$n; $i++) {
        for ($j=0, $n2=sizeof($quotes[$i]['methods']); $j<$n2; $j++) {
// set the radio button to be checked if it is the method chosen
          $checked = (($quotes[$i]['id'] . '_' . $quotes[$i]['methods'][$j]['id'] == $shipping['id']) ? true : false);         
?>
      <tr class="table-selection">
        <td>
          <strong><?php echo $quotes[$i]['module']; ?></strong>
          <?php
          if (isset($quotes[$i]['icon']) && tep_not_null($quotes[$i]['icon'])) echo '&nbsp;' . $quotes[$i]['icon'];
```

I don't see any free shipping icon configuration on admin, therefore I propose to delete this, resulting:
```php
<div class="panel-heading"><strong><?php echo FREE_SHIPPING_TITLE; ?></strong></div>
```

**Comment by katapofatico** [comment]
Maybe I don't see something: correct me if I miss anything

**Comment by gburton** [comment]
Pretty sure this is a direct mirror from osCommerce2, so this bug has probably been around for many years.  I see no reason why we cannot remove per your suggestion.  Send a pull-req?

**Comment by BrockleyJohn** [comment]
It probably means you could take out all the free shipping stuff and no-one would care!

**Comment by katapofatico** [comment]
@BrockleyJohn  8D

**Comment by gburton** [comment]
@katapofatico push the fix?

**Comment by katapofatico** [comment]
Maybe I forgot it! I'm on 10 days holiday trip: I have not my dev machine. If you don't mind please push it: the solution is on my first comment, it's very easy. Excuse me and thanks!
