### ISSUE TITLE
Admin -> Configuration -> Maximum Values -> New Products Listing ->

### ISSUE THREAD

**Issue by Cozaki** [gburton/Responsive-osCommerce#262]
Clean installation of OSC 234BS3 EDGE

*********************
Admin -> Configuration -> Maximum Values -> New Products Listing -> 
Please make any necessary changes

New Products Listing
Maximum number of new products to display in new products page
I Choose 10 & saved.
New products page shows 28 new products

**Comment by gburton** [comment]
New Products uses product_listing module https://github.com/gburton/Responsive-osCommerce/blob/master/products_new.php#L115

Product Listing module uses MAX_DISPLAY_SEARCH_RESULTS https://github.com/gburton/Responsive-osCommerce/blob/master/includes/modules/product_listing.php#L13

Max Display Search Results is therefore the controller for number of items on this page https://github.com/gburton/Responsive-osCommerce/blob/master/install/oscommerce.sql#L714
