### ISSUE TITLE
Admin -> Configuration -> Product Listing-> Display Product Price

### ISSUE THREAD

**Issue by Cozaki** [gburton/Responsive-osCommerce#271]
Clean installation of OSC 234BS3 EDGE

Admin -> Configuration -> Product Listing
Display Buy Now column 

Please make any necessary changes

Display Product Price
Do you want to display the Product Price
0 or 1, it always show the price

I think these are important settings ?
Showing prices and/or buy now buttons Yes or No depending on the need of the shopowner.

Anyway having these settings that doesn affect the shop is bit stupid

Good luck

**Comment by gburton** [comment]
These are unimportant.  And will be looked at sometime in the future.
Please stop posting low level bugs, thanks.

**Comment by Cozaki** [comment]
You cannot run before you learn walking.

Low level bugs? These are the start of every shop. 
Think starting debugging the admin would be priority.
Getting the base working properly.
Delete or fix it

success

**Comment by gburton** [comment]
Feel free to fork and fix.  Send pushes.  I dont want more "words", I want action.

I am not interested in low level "bugs", that in fact have deliberately been left active for a reason.
