### ISSUE TITLE
Removing 960gs

### ISSUE THREAD

**Issue by Piernas** [gburton/Responsive-osCommerce#273]
Correct me if I'm wrong but isn't 960 grid system unused in this oscommerce revision?
If that's the case I think it would be safe to remove those files from install.

**Comment by gburton** [comment]
There is lots of things that need to be cleaned.  Images, Buttons, 960, Languages and more.
If you want to go ahead and rip out 960, and test everything works OK after, go ahead.  Then push the changes to me...

**Comment by Piernas** [comment]
Done with grid system. Will do with language files once I complete spanish translation.

**Comment by gburton** [comment]
You have tested this fully ?

**Comment by Piernas** [comment]
Nothing. Searched across the whole set of files and it was not referenced. Everything seems to work ok on both sides.
