### ISSUE TITLE
Unused function tep_navbar_search in html_output

### ISSUE THREAD

**Issue by Piernas** [gburton/Responsive-osCommerce#276]
Seems to be a forgotten, never called anywhere function for navbar. Seems to be safe to remove unless it's there for any future purpose.

**Comment by gburton** [comment]
I think that was used in a very early version.  It can be removed.  Push?

**Comment by Piernas** [comment]
Will try. I'm having troubles understanding how to push only one single commit when I have several.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/commit/722b95594d3e0f96f1eda2f79f43eb9b197fca87
