### ISSUE TITLE
Navbar language menu does not keep selected language

### ISSUE THREAD

**Issue by Piernas** [gburton/Responsive-osCommerce#277]
Main title doesn't update to current language when swithching but still displays default language instead.

**Comment by gburton** [comment]
Example URLs?

**Comment by Piernas** [comment]
http://hobbycrash.com/test/index.php?language=es

**Comment by gburton** [comment]
Looks like you have not translated into Spanish?

https://github.com/gburton/Responsive-osCommerce/blob/master/includes/languages/english/modules/navbar_modules/nb_languages.php#L16 (as an example).

**Comment by Piernas** [comment]
Oh, thank you! I was supposing it used the language name from the database.
