### ISSUE TITLE
Padding fix for "0 items" in shopping_cart navbar module.

### ISSUE THREAD

**Issue by Tsimi78** [gburton/Responsive-osCommerce#279]
There seems to be a padding issue when there is no item in cart.
Only visible in navbar collapsed mode (XS viewport)
Recommend (according [Non-nav links](http://getbootstrap.com/components/#navbar-links))

`echo '<li class="nav navbar-text">' . MODULE_NAVBAR_SHOPPING_CART_NO_CONTENTS . '</li>';`

to this

`echo '<li><a href="#" class="navbar-link">' . MODULE_NAVBAR_SHOPPING_CART_NO_CONTENTS . '</a></li>';`

**Comment by skleiner** [comment]
I see this on smartphone. Nothing in cart...the icon is far left relative to others, with an item in cart..icon is aligned with others.

**Comment by gburton** [comment]
Unfortunately it's not a link, so cannot have a href to try to fix it.  Can you find another way?

**Comment by Tsimi78** [comment]
How about this.
`echo '<li class="navbar-text nolink">' . MODULE_NAVBAR_SHOPPING_CART_NO_CONTENTS . '</li>';`

add this to user.css or custom.css
`@media (max-width: 767px) {
.nolink  {
  padding-left: 15px;
}
}`

**Comment by gburton** [comment]
Is it a bootstrap bug?

**Comment by gburton** [comment]
Or...we could also make it a link.  And be done with it.
Thoughts?

**Comment by Tsimi78** [comment]
No idea if it is a bootstrap bug but adding any non-link to the navbar ends up with no padding when going lower then 768px. 
If you would make it a link, then the question would be a link to what? Shopping cart page?

**Comment by gburton** [comment]
Shopping Cart Page.

Problem appears to be located here: 

`.navbar-text {
  margin-top: 15px;
  margin-bottom: 15px;
}
@media (min-width: 768px) {
  .navbar-text {
    float: left;
    margin-right: 15px;
    margin-left: 15px;
  }
}`

which is saying:  if viewport >768 add a 15px margin left and right

Two questions come from that;

1.  why have a margin left and right only when above 768
2.  why has nobody else (other users of bootstrap) seen similar problem

and 1 more question;

3.  is our use of navbar-text on a li the correct approach ?

**Comment by gburton** [comment]
I found a couple of bits and pieces referencing similar problems.  
We can do it as a link (shopping_cart) or we can do it as an extra bit of .css.  
Your choice @Tsimi78 

I like [this]https://github.com/gburton/Responsive-osCommerce/issues/279#issuecomment-194816387 into https://github.com/gburton/Responsive-osCommerce/blob/master/custom.css

**Comment by Tsimi78** [comment]
I agree, [this](https://github.com/gburton/Responsive-osCommerce/issues/279#issuecomment-194816387) seems to be the quickest and cleanest way. Adding a link to an empty shopping cart page is not really useful and IMO makes not much sense.

**Comment by gburton** [comment]
OK.  Push it?

**Comment by Tsimi78** [comment]
I hope I did it correctly. You should see now a pull request.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/commit/ed0944244ade09fc210d44a0161c3a9d4c8d70dd
