### ISSUE TITLE
Micro-Data product_info.php itemprop="price"

### ISSUE THREAD

**Issue by azpro-git** [gburton/Responsive-osCommerce#280]
This fix  https://github.com/gburton/Responsive-osCommerce/commit/8e00b6cc6b190d282e422f776dc9987986c943bb gives IMHO a problem if shopowner uses , in stead of . for $this->currencies[$currency_type]['decimal_point'].

Could be avoided by relying on $currencies->calculate_price and using number_format :
`	  $products_price = '<span itemprop="price" content="' . number_format($currencies->calculate_price($product_info['products_price'], tep_get_tax_rate($product_info['products_tax_class_id'])),2) . '">' . $currencies->display_price($product_info['products_price'], tep_get_tax_rate($product_info['products_tax_class_id'])) . '</span>';`

**Comment by gburton** [comment]
https://schema.org/price
Use '.' (Unicode 'FULL STOP' (U+002E)) rather than ',' to indicate a decimal point. Avoid using these symbols as a readability separator.

Push?

**Comment by gburton** [comment]
No push.

**Comment by azpro-git** [comment]
Sorry - forgot to reply earlier ... Should be pushed IMHO ...

**Comment by gburton** [comment]
@azpro-git send a push

**Comment by gburton** [comment]
No Push.  Closed.
