### ISSUE TITLE
Problem with navbar

### ISSUE THREAD

**Issue by dbusr** [gburton/Responsive-osCommerce#284]
The navbar module in the latest release doesn't work.  The problem seems to be that MODULE_CONTENT_NAVBAR_INSTALLED is not defined. From the looks of the code, this is supposed to be a list of modules though I don't see the purpose of it in this module, which is why I didn't supply a fix.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/pull/286/files#diff-6cf84f05b277528edf3e7c81eb26cce0
