### ISSUE TITLE
Show categories box by page

### ISSUE THREAD

**Issue by katapofatico** [gburton/Responsive-osCommerce#295]
As a Shop Owner, I want to show categories box on several pages (index.php), and not in other ones (checkout.php, product_info.php). Then...
As Shop Developer I want to offer configuration on /admin/ about in which pages the categories box is visible or not, as already exists on Datepicker jQuery Header Tag module. Therefore I will modify bm_categories.php. adapting the MODULE_HEADER_TAGS_DATEPICKER_JQUERY_PAGES functionality.

What do you think? Are you interested on it? I'm going to do it on my branch. Any idea to enrich it will be appreciated.

**Comment by gburton** [comment]
Go ahead.  Remember that index.php has three different pages...

**Comment by katapofatico** [comment]
I have it yet, but:

1. The change about this issue is only on bm_categories.php. However, in the comparing tool appears another change on html_output.php, several commits before, resolving a PHP Warning. I'm sorry about this mixed state: I don't know how to resolve this situation: Can you pull only the single change on bm_categories.php?

2. As I comment on the commit, I treated index.php as a single page: Are you proposing to distinguish between the 3 pages? Personally, I'm not interested on it, but if you give me the path I can develop it.

**Comment by gburton** [comment]
index.php needs to be treated as 3 pages;  fron page, category page, manufacturer page.  How you do that is up to you.  It's not something I have the time to look into.  If you get it all working, send a push.
