### ISSUE TITLE
Include order id property in order class

### ISSUE THREAD

**Issue by Piernas** [gburton/Responsive-osCommerce#301]
Currently order clas does not include order id, so all code still relies on reading $HTTP_GET_VARS['order_id'] again and again or creating an $oID variable even if the class has been initialized. I think code would be cleaner and more logical to add the variable to the class.
It's easy to modify the class and hunt all those places wher it is done, I can do it. Is it ok to go and change it?

**Comment by gburton** [comment]
@piernas it would change too much core code across files.  However, you could modify the class file only which would be helpful for future code changes.  

orders.orders_status would also be useful to have as class output.  

Remember to first update your Master from my Master, then Branch, and make the changes in that Branch - makes it easy to push to me, and for me to then commit.

**Comment by Piernas** [comment]
Syill having issues learning how to use github, when I push somehing it adds previously pushed content and still not found how to avoid it. I'll try, please let me know if there are still garbage.

**Comment by Piernas** [comment]
There's a problem with orders status as I mentioned in the forums some time ago in : [http://forums.oscommerce.com/topic/399551-orders-class/#entry1725173](url)

This is the current code from orders class in the shop side about order status:
`'orders_status' => $order_status['orders_status_name'],`
and in the admin side:
`'orders_status' => $order['orders_status'],`

I think we should use the same property name in both sides, but this implies to modify one of them. We should debate what to do with it.

I'd personally use this schema:
`'orders_status_id' => $order['orders_status'],
                          'orders_status_name' => $order_status['orders_status_name'],`

**Comment by gburton** [comment]
Simply add in the two new entries as you suggest.  
Leave already existing things as is.

**Comment by Piernas** [comment]
I've done it. But when Itry to make a pull request it takes two commits instead the last one. Is there a simple way to send only latest commit?

**Comment by BrockleyJohn** [comment]
The latest commit only has the latest changes. You want all the commits!

If you're saying that the previous commit didn't have anything useful and you had to undo it, what you should have done is reverse the previous commit and start the change again.

**Comment by Piernas** [comment]
I mean I made two commits; one for order id (already pulled) and a second one for order status. If I open a new pull request it adds the already pulled first ccommit. Should I start a branch for every single commit?

**Comment by Piernas** [comment]
#306 is the first one.

**Comment by gburton** [comment]
You seem to be doing more than you originally spoke of.  Closed.

You should have a Master that matches exactly my Master.  
You then Branch it, and make changes in that Branch.
You then push the changes to my Master.
If I accept your change, it goes into my Master.
You then pull those accepted changes into your Master.
YOUR MASTER ALWAYS MATCHES MY MASTER.

If you move onto a different project, make a new Branch for it.

Closed.

**Comment by Piernas** [comment]
I'm sorry. I misunderstood the way to use branches. My main branch matches yours, but I tried to do two separate small changes under a sub-branch, now I se it can't be done. Will do one branch exclusively for one change even if it's small. Sorry again.
