### ISSUE TITLE
Automatic function loading

### ISSUE THREAD

**Issue by dbusr** [gburton/Responsive-osCommerce#304]
I suggest adding module-like code to load functions? For just about all addons, the general.php file is altered to include functions for the addon. It would be a relatively minor change to include a file that reads in all of the files in a user-functions directory. This would make altering the core code unnecessary and make installing addons a little easier. I can't think of a downside to it though I just thought of it and may be missing something. Any thoughts?

**Comment by gburton** [comment]
@dbusr - properly coded addons do not change core files.  Avoid old crappy addons...

Thoughts ?

**Comment by Kymation** [comment]
If the Addon is a module, adding the function code to the module file works well enough. Is there any advantage to adding a separate file? Are there cases where a function is needed for an Addon that is not a module?

**Comment by BrockleyJohn** [comment]
@gburton - totally agree on the catalog side; the modules give you the ability to add whatever you need wherever there. Admin's a bit harder... my first cut of cross-sell for bs has caching which of course craps all over admin/functions/general and admin/categories, while modular admin categories is supposed to hit core code ;)

**Comment by dbusr** [comment]
There are many good addons not converted to work as modules, or for this version for that matter. Converting some to be a module would be very difficult and not worth the effort. Taking a stand of tough luck for those doesn't help the project, in my opinion. Especially since adding a small piece of code to handle them would not take much.

**Comment by newburns** [comment]
Conversation like this is best left to the forums. Github is for the progression of the code, and the forums have a larger user base to debate whether something is good for the progression of the code.
Bring this up in the forum, and you will get a more defined response. But I think Github should be left for code development only.

**Comment by gburton** [comment]
@dbusr If you want to add in crappy modules, go ahead.  It's what we want to get away from.  Get the addon maker to remake it properly, or get a whole new addon made to proper standard.

@newburns Github is the place for all conversation.  I'm not interested in debate on the Forum.
