### ISSUE TITLE
Account history info modularization

### ISSUE THREAD

**Issue by Piernas** [gburton/Responsive-osCommerce#308]
Almost done with account history info modularization, as I need this to add a "pay now" button as a module depending on order status. It follows the same guidelines as other pages. Do you consider interesting to be added?

**Comment by gburton** [comment]
Yes, for sure.  But only modularise the bits that it already has (not the bits you need to add for your purpose) ...  Thanks!

**Comment by Piernas** [comment]
Of course, the meaning of doing for me is adding a custom paypal button as I did in my current shop, but it won't be included. Maybe when it's done I'll share it as an addon.
I'm just finishing language files and testing. For those who test it please take a look at the templates as I'm not exactly a genius with bootstrap and I may have done something odd.

**Comment by Piernas** [comment]
Still working on it. When adding the downloads part I've noticed that some modules are hidden (delivery and billing address, as well as order history timeline). That makes bootstrapped modules to change their position in some cases.
Seems to me that the download module would need some work on it as it doesn't look as the rest of the page; Anyway I'll just add a fa-download icon and leave as is.

**Comment by gburton** [comment]
Sure, you don't have to make things 100% perfect.  The testers and me can advise and/or change things.  Think of it as you providing the foundation, then the rest of us (and you) building more on it, painting it, and so on.

**Comment by Piernas** [comment]
Here it is #310

**Comment by Piernas** [comment]
Found an small issue on downloads module just after uplading. Forgot to change $last_order to SoID, so download.php is not being correctly called as order id is not being ammended.

**Comment by gburton** [comment]
Go back to your Branch, make the changes "Forgot to change $last_order to $oID" and push them.  Also could you remove the <!-- comments in each template file.  I hate having to have those in files.

So, all you need to do is open the Branch in which you are working.  Make the changes to the relevant files.  Push.  Those changes will add to this one.

Suggestion:  Use Sourcetree rather than Github Desktop.  Sourcetree is a lot more advanced, yet a lot more easy to work with...

**Comment by Piernas** [comment]
Done! I'll take a look at sourcetree, thanks for the suggestion.

**Comment by Kymation** [comment]
Gary -- Please do not remove the headers from any of the files. The license grant in the header is the only thing that allows others to use or modify this code. A file without the license is copyright to the author, and only the author has the right to use it.

**Comment by gburton** [comment]
@Kymation - you're the first to mention it...don't know why you brought it up?

I want @Piernas to remove comments from the template files, not anything else.

**Comment by Kymation** [comment]
I brought it up because you seem to be creating a problem. I don't know why you are ding this. Can you tell me your reason?

If you re removing the headers from the template files, then only the template files become unusable. Why only the template files?

**Comment by gburton** [comment]
There are no headers in template files.  What makes you think there is ?

**Comment by Kymation** [comment]
I'm aware that there are no headers in your template files. I am trying to tell you that this is a problem. What makes you think that this is not a problem?

**Comment by gburton** [comment]
Because I am the author of every template file, I grant anyone use of - no problem.

**Comment by Kymation** [comment]
Where have you granted permission? 

Even if you have granted permission, this is not compatible with the GPL license on every other file in the osCommerce diostribution, and therefore cannot be included with or used with osCommerce. You're creating quite a mess here.

**Comment by gburton** [comment]
I'd say "forget about it"... move on.

**Comment by Kymation** [comment]
I strongly suggest that you consult your legal counsel before "moving on". 

In any case, I will continue to put the legal headers on every single file that i write.

**Comment by Piernas** [comment]
Is it needed to add the license to every single file instead including a license file with distribution?

**Comment by Kymation** [comment]
Yes. What happens when I copy several files from osCommerce to use in an unrelated project?

**Comment by Piernas** [comment]
I'm one of those who feels dizzy readig legal stuff. I know nothing abut legal issues, but for me it's the same as deleting the header and using it on an unrelated project, or taking a part of it.

Same as an industrial design, you don't mark every piece of it but no one can take a bit alone to use it if it is registered.

**Comment by Kymation** [comment]
I find copyright/patent/trademark law interesting and have studied it a bit. Not an expert, but I want to know enough to stay out of trouble.

Every page of code that is published here is under copyright. Consider it an industrial design that has been registered.

**Comment by oitsuki** [comment]
You have no right to change the license. The BS is under Oscommerce that's all.
You can add information or add a license compatible with under Oscommerce.

 * file name
 * @copyright Portions Copyright osCommerce
 * @license GNU Public License V2.0 (example)

**Comment by Kymation** [comment]
What license? Gary has removed the license, so there is none.

**Comment by gburton** [comment]
1.  If something was never there in the first place, it cannot be removed.
No preamble has been removed from any file.

2. There is nothing in the GPL which states that all files *must* have preamble.
I have no doubt you will point me at a certain paragraph, which states "should", but "should" is not "must".

3.  Any file without copyright is automatically copyright to it's creator, I think we all know that.

4.  I might put some preamble on these copyrighted files, but it might not be GPL, it might be a compatible license.  Undecided.

**Comment by BrockleyJohn** [comment]
IIRC there's a stipulation that all code uploaded to addon.osc.com must be GPL. That's prevented my uploading addon code based on other licences in the past.

**Comment by Kymation** [comment]
GPL or compatible. Code licensed under BSD or MIT (among others) has  been acceptable in the past.
