### ISSUE TITLE
Administration tool for modules - Work in progress

### ISSUE THREAD

**Issue by Piernas** [gburton/Responsive-osCommerce#313]
With growing amount of modules installed it's starting to be confusing what module is installed, enabled or even uploaded to the server. I've been working on a config page that will allow to see what modules you have in a section at a glance. Boxes will need their own page, as content modules.
Attached is what I've done so far. Buttons still doesn't do anything, but if you want to take a look at it you can easily install by copying the two files inside the zip attached to your server and going to admin -> modules. It doesn't overwrite any files or config so no hurt at all.

@gburton please let me know if you consider it of interest for this project. I know you are not much interested in general on admin side but for me it is important as it's part of my everyday work. Any feedback will be welcome. 

PS. code is very ugly but it's just a test, so please forgive me!!

I've also opened [http://forums.oscommerce.com/topic/409257-administration-tool-for-modules-wip/](url)

[modulitos.zip](https://github.com/gburton/Responsive-osCommerce/files/188767/modulitos.zip)

**Comment by skleiner** [comment]
I haven't looked at the code but this has merit. I have been in the position trying to find this or that module. This would especially be useful for modules on the server but not installed.

**Comment by gburton** [comment]
It might make a very nice addon?

**Comment by Piernas** [comment]
@gburton just made and published it for content modules that are mixed in one page (more useful than for the rest of the modules that has their own page), it's on the oscommerce download addon section.
I finally used a couple of dirty tricks to change the visuals for install routine and put responsive divs on the page without bootstrap. You can close this issue, or if you consider it useful, remove the tricks and add it to the code. Anyway I think content modules should go to tabs or separate pages - I now have about 60 or so and it's a mess! :-)
