### ISSUE TITLE
tep_class_exists - obsolete must go to compatibility.php?

### ISSUE THREAD

**Issue by Piernas** [gburton/Responsive-osCommerce#314]
Just found this function inside admin/includes/functions/general.php:

`////
// Wrapper for class_exists() function
// This function is not available in all PHP versions so we test it before using it.
  function tep_class_exists($class_name) {
    if (function_exists('class_exists')) {
      return class_exists($class_name);
    } else {
      return true;
    }
  }`

On a quick search on the net I couldn't found what PHP version introduced tep_class_exists. I didn't find any report of availabiliy; It can be obsolete (seems that every php 5.X has it) or if not, then should be moved to compatibility.php.

This is used in:
- admin\includes\modules\dashboard\d_security_checks.php
- admin\modules.php
- admin\action_recorder.php
- admin\modules_content.php

**Comment by Kymation** [comment]
class_exists() was introduced in PHP 4. Why would we need to support PHP 3?

**Comment by Kymation** [comment]
Also, I see that we are changing all of the class constructors to the __construct() form, which was introduced in PHP 5. That will make any attempt at compatibility with PHP 4 and older worthless.

**Comment by gburton** [comment]
MIght it be simpler to:

```
function tep_class_exists($class_name) {
  if (function_exists('class_exists')) {
     return class_exists($class_name);
   } else {
     return true;
   }
 }
```

To:

```
function tep_class_exists($class_name) {  
  return class_exists($class_name);
}
```

**Comment by Piernas** [comment]
Or even just leave as is. It's your choice. I  personaly prefer to get rid of unused or obsolete junk.
I also found some completely unused functions. I can suggest to remove them
There are also some functions that only belong to one file (for example those related to system information) that might be moved to their own page instead of being in common files.

**Comment by gburton** [comment]
The point of putting a native php function inside a self made function is so that if an update happens to the native php function, you only need to change 1 time in 1 place and all is well.

**Comment by Piernas** [comment]
That's fine But that leaves us on having retrocompatibility even when it's not needed anymore. The native function appeared in 2001,  has not changed since then and it's not expected to change.

Do you want me to remove other completely unused functions I found on that file?
