### ISSUE TITLE
HTTP Authentication has not been set up for the osCommerce Administration Tool - please set this up in your web server configuration to further protect the Administration Tool from unauthorized access.

### ISSUE THREAD

**Issue by bobnzer** [gburton/Responsive-osCommerce#319]
Is this the place to put feedback?

The use of "HTTP Authentication" with cPanel/WHM is discouraged, therefore the option was removed from the "Tweak Settings" interface. 

This is documented in the 11.44 Release Notes:

The following settings are no longer available in the Tweak Settings interface:

Urchin Installation Path
Enable HTTP Authentication

More information about why we discourage it's use is available here:

Authentication Methods

Thank you.

**Comment by BrockleyJohn** [comment]
The link to their justification for turning off http authentication hasn't come through - please provide it.

**Comment by bobnzer** [comment]
The warning has now dissappeared

**Comment by bobnzer** [comment]
It went away when i protected the /ext/ directory so not sure why

**Comment by Piernas** [comment]
[https://documentation.cpanel.net/display/CKB/Basic+Security+Concepts#BasicSecurityConcepts-AuthenticationMethods](url)

**Comment by bobnzer** [comment]
ok all good so far. Thanks for the quick response. Looks good on the mobile as well. I dont know much code but I will give feedback while I am setting it up. Thanks all. I couldn't see where to go to buy one of the developers templates?

**Comment by bobnzer** [comment]
This what i got for the search "HTTP Authentication" with cPanel/WHM"

https://forums.cpanel.net/threads/http-authentication.413432/

**Comment by gburton** [comment]
You need to protect the admin area, using either usual htaccess/htpasswd protection from with cpanel OR the inbuilt method provided by osCommerce.  Try using the inbuilt method.

**Comment by gburton** [comment]
> couldn't see where to go to buy one of the developers templates?

http://www.oscommerce-templates.co.uk/#responsive

Thanks
