### ISSUE TITLE
navbar modules "Home" css problem

### ISSUE THREAD

**Issue by BecRoM** [gburton/Responsive-osCommerce#321]
If you put some of navbar modules items in "home", their styles have issues (color, position, size of navbar)

**Comment by BecRoM** [comment]
Changing this in includes/modules/..../navbar.php

`    <?php
    if ($oscTemplate->hasBlocks('navbar_modules_home')) {
      echo '<div class="navbar-header">' . PHP_EOL;
      echo $oscTemplate->getBlocks('navbar_modules_home');
      echo '</div>' . PHP_EOL;
    }
    ?>  `

by this:

`    <?php
    if ($oscTemplate->hasBlocks('navbar_modules_home')) {
      echo '<div class="navbar-header"><ul class="nav navbar-nav">' . PHP_EOL;
      echo $oscTemplate->getBlocks('navbar_modules_home');
      echo '</ul></div>' . PHP_EOL;
    }
    ?>  `

And adding this in user.css:

`@media (max-width: 767px) {
.navbar-nav > li {
  float:left;
}
}`

Seems to work correctly

**Comment by gburton** [comment]
The only one that should go in "home" is brand.  All others go right or left.

**Comment by BecRoM** [comment]
In this case should remove "home" option in those modules

**Comment by gburton** [comment]
Why?  Maybe, like you, other want those things in the Home.  
In which case, they put them in Home, then amend the language file to get rid of the <li>

It is flexible this way.
