### ISSUE TITLE
Discuss:  seo_title

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#322]
Gives the ability to make a more "seo" name...

**Comment by gburton** [comment]
So, let's take a category_seo_title.  Where should this manifest itself?

The <title> for sure.
The breadcrumb ?
The category name in index.php ?  <-- unlikely

**Comment by gburton** [comment]
So, let's take a category_seo_title. Where should this manifest itself?

- The title (in the meta header) 
  - for sure
- The breadcrumb
  - ?
- The category name in index.php
  - unlikely

**Comment by skleiner** [comment]
I've tweaked my query to show the SEO title in the breadcrumb. Reason being to improve page seo.  For example in including the seo title in breadcrumbs is a plus, it's an itemprop name. I hope I have that concept correct.

**Comment by MOPS-DanCole** [comment]
I was just using it in the header...ie right out of the box but I think Steve has a good idea adding it to the breadcrumb.  I like using the usual/regular category name on the index.php...that way you can keep it brief on the dropdown list etc and have a more appropriate SEO title where it counts.
