### ISSUE TITLE
Paypal App - Payments Standard

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/Responsive-osCommerce#323]
If a PDT identity token is not set, the module fails in checkout_process.php on return from paypal - fails to find /includes/apps/paypal/modules/PS/api/GetTransactionDetails.php

It's caused by line 599 in includes/modules/payment/payal_standard.php which is:
          $details = $this->_app->getApiResult('PS', 'GetTransactionDetails', array('TRANSACTIONID' => $HTTP_GET_VARS['tx']), (OSCOM_APP_PAYPAL_DP_STATUS == '1') ? 'live' : 'sandbox');

The workaround is to make sure Payment Data Transfer is turned on in the Paypal account, and set the PDT identity token in the module settings. This avoids executing the code that fails.

**Comment by gburton** [comment]
Setting up PDT has always been the advice given (when using Paypal Standard).

**Comment by BrockleyJohn** [comment]
Fair enough - but falling over in a heap if it's not set isn't the best coding practice! When first debugging you look everywhere for the missing file before deciding it's not anywhere and investigating why the page looked for it.

I am happy to code up the mod to validate that PDT id token is set if you'd be in the slightest interested in pulling it.

**Comment by gburton** [comment]
Unless the user followed the instructions to set the PDT...

You need to do this at the forum, as this is an Addon.  Bring it to the attention of HPDL.

**Comment by Piernas** [comment]
Won't paypal app be added to the core then?
