### ISSUE TITLE
Font Awesome 4.6.0

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#330]
Uplift to 4.6
https://articles.fortawesome.com/font-awesome-4-6-released-d7213342698a

**Comment by gburton** [comment]
Buttons have FA icons.  Should we add aria-hidden="true" to remove them on those buttons which use FA for decoration purposes?  See http://fontawesome.io/accessibility/

**Comment by gburton** [comment]
Examples from http://fontawesome.io/accessibility/

`<a href="path/to/shopping/cart">
  <i class="fa fa-shopping-cart" title="View 3 items in your shopping cart" aria-hidden="true"></i>
  <span class="sr-only">View 3 items in your shopping cart</span>
</a>`

**Comment by BrockleyJohn** [comment]
Seems like a good thing in principle...

I wonder how 234bs rates generally for accessibility and where this would come in a prioritised list of issues.
Armed with all the knowledge that 10 minutes and google can provide, I think it might be a good idea to start by checking that all inputs have an accessible name (see the fifth rule here [http://w3c.github.io/aria-in-html/](url))

I'm not sure where to begin on an effective testing strategy

**Comment by gburton** [comment]
@BrockleyJohn I spent many hours updating inputs, so they *should* mostly be good (for label and id)... I may have missed some, but not many.

**Comment by BrockleyJohn** [comment]
@gburton I'm glad to hear it - looks like we're on the same page of the map but you set off on the journey some time ago.
I found some web-page checking tools, which will work for the catalog and create account but presumably not for the checkout process. They all nag about header hierarchy along with a bunch of other stuff. I quite liked this one:
[http://wave.webaim.org/report#/http://bromleybr.co.uk/bsgit/](url)
I'm going to try out some of this viking's suggestions:
[http://www.karlgroves.com/2013/09/05/the-6-simplest-web-accessibility-tests-anyone-can-do/](url)

**Comment by skleiner** [comment]
@gburton This is a new concept to me, I've read your links and googled some more.  Could you point to a page shop side that has an example of FA for decorative purposes only? It'll help me grasp this better.

**Comment by gburton** [comment]
@skleiner - there actually are not that many.  Off the top of my head maybe the search button?

**Comment by gburton** [comment]
Look at this as part of finalised review.
