### ISSUE TITLE
Selected language in language navbar module is still hardcoded

### ISSUE THREAD

**Issue by raiwa** [gburton/Responsive-osCommerce#333]
define('MODULE_NAVBAR_LANGUAGES_SELECTED_LANGUAGE', '<abbr title="Selected Language">L:</abbr> English <span class="caret"></span>');

**Comment by gburton** [comment]
Explain further?  What is the exact problem ?

**Comment by raiwa** [comment]
English is always shown as selected language, even the language has been change to another

**Comment by raiwa** [comment]
Possible fix:
<li class="dropdown">
  <?php
  if (!isset($lng) || (isset($lng) && !is_object($lng))) { 
    include(DIR_WS_CLASSES . 'language.php');
    $lng = new language;
  }
  reset($lng->catalog_languages);
  while (list($key, $value) = each($lng->catalog_languages)) {
  	if ($language == $value['directory']) {
?>
  <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo '<abbr title="Selected Language">' . MODULE_NAVBAR_LANGUAGES_SELECTED_LANGUAGE . '</abbr>' . $value['name'] . '<span class="caret"></span>'; ?></a>
<?php
		}
  }
  if (count($lng->catalog_languages) > 1) {
    ?>
    <ul class="dropdown-menu">
      <?php   
      reset($lng->catalog_languages);
      while (list($key, $value) = each($lng->catalog_languages)) {
        echo '<li><a href="' . tep_href_link($PHP_SELF, tep_get_all_get_params(array('language', 'currency')) . 'language=' . $key, $request_type) . '">' . tep_image(DIR_WS_LANGUAGES .  $value['directory'] . '/images/' . $value['image'], $value['name'], null, null, null, false) . ' ' . $value['name'] . '</a></li>';
      }
      ?>
    </ul>
    <?php
    }
  ?>
</li>

**Comment by raiwa** [comment]
in language file:
  define('MODULE_NAVBAR_LANGUAGES_SELECTED_LANGUAGE', 'L: ');

+ add global $language to nb_languages module

**Comment by raiwa** [comment]
Sorry, not good posting code as text:
templates/languages.php:
`<li class="dropdown">
  <?php
  if (!isset($lng) || (isset($lng) && !is_object($lng))) { 
    include(DIR_WS_CLASSES . 'language.php');
    $lng = new language;
  }
  reset($lng->catalog_languages);
  while (list($key, $value) = each($lng->catalog_languages)) {
  	if ($language == $value['directory']) {
?>
  <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo '<abbr title="Selected Language">' . MODULE_NAVBAR_LANGUAGES_SELECTED_LANGUAGE . '</abbr>' . $value['name'] . '<span class="caret"></span>'; ?></a>
<?php
		}
  }
  if (count($lng->catalog_languages) > 1) {
    ?>
    <ul class="dropdown-menu">
      <?php   
      reset($lng->catalog_languages);
      while (list($key, $value) = each($lng->catalog_languages)) {
        echo '<li><a href="' . tep_href_link($PHP_SELF, tep_get_all_get_params(array('language', 'currency')) . 'language=' . $key, $request_type) . '">' . tep_image(DIR_WS_LANGUAGES .  $value['directory'] . '/images/' . $value['image'], $value['name'], null, null, null, false) . ' ' . $value['name'] . '</a></li>';
      }
      ?>
    </ul>
    <?php
    }
  ?>
</li>    `

**Comment by gburton** [comment]
Cannot recreate.  Works perfect for me, tested in Français & English.
So long as MODULE_NAVBAR_LANGUAGES_SELECTED_LANGUAGE is updated per language, all is well.

**Comment by raiwa** [comment]
OK, sorry didn't get this, had not translated language file ohppss
