### ISSUE TITLE
undefined MODULE_HEADER_TAGS_GRID_LIST_VIEW_STATUS in product_listing.php if ht_grid_list_view.php is not installed

### ISSUE THREAD

**Issue by raiwa** [gburton/Responsive-osCommerce#334]
Fix:
 includes/modules/product_listing.php line 97:
`        if ( ( defined('MODULE_HEADER_TAGS_GRID_LIST_VIEW_STATUS') && MODULE_HEADER_TAGS_GRID_LIST_VIEW_STATUS == 'True') && (strpos(MODULE_HEADER_TAGS_GRID_LIST_VIEW_PAGES, basename($PHP_SELF)) !== false) ) {
`

**Comment by gburton** [comment]
@raiwa 
1.  explain the problem.
2.  fork and provide code

Otherwise it will get closed.  Thanks

**Comment by raiwa** [comment]
If the Header tag module ht_grid_list_view.php is not installed, the product_list module (includes/modules/product_listing.php) will throw a undefined constant error for MODULE_HEADER_TAGS_GRID_LIST_VIEW_STATUS.

I'll fork the fix tomorrow.
