### ISSUE TITLE
Also purchased checking

### ISSUE THREAD

**Issue by dbusr** [gburton/Responsive-osCommerce#340]
If the also purchased minimum value in the settings is set to 0, the title for that module is still displayed. This line in includes/modules/also_purchased_products.php 

if ($num_products_ordered >= MIN_DISPLAY_ALSO_PURCHASED) { 

should be changed to something like

if ($num_products_ordered && $num_products_ordered >= MIN_DISPLAY_ALSO_PURCHASED) {

**Comment by gburton** [comment]
I cannot recreate.  If (in admin) "Maximum number of products to display in the 'This Customer Also Purchased' box" is set to zero, no products show and the title disappears.  Could you test again.

**Comment by dbusr** [comment]
Hello,

I re-tested and it fails here. The code in the module is like this:

if ($num_products_ordered >= MIN_DISPLAY_ALSO_PURCHASED) {

build the list of products

}

Show the title

Show the products


No checking is done if the product list exists so the title is always shown. The closing bracket needs to be move to after the show the products code.

g> I cannot recreate. If (in admin) "Maximum number of products to
g> display in the 'This Customer Also Purchased' box" is set to zero,
g> no products show and the title disappears. Could you test again.
g> —
g> You are receiving this because you authored the thread.
g> Reply to this email directly or view it on GitHub 


                  


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by gburton** [comment]
Thanks for testing again.  

This:
https://github.com/gburton/Responsive-osCommerce/blob/master/includes/modules/also_purchased_products.php#L16

ends at
https://github.com/gburton/Responsive-osCommerce/blob/master/includes/modules/also_purchased_products.php#L47
