### ISSUE TITLE
Microdata

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#343]
I would like to microdata every part of the public-facing shop-side as much as possible, not bothered about what happens once the customer is logged in (eg looking at account_history) as Search Engines never see these pages. It's only about public-facing pages in the shop...

Microdata is **the most important** piece of the SEO puzzle - aka "the next big thing".

So far, what has been microdata'd:
- breadcrumb
- product page
- product reviews page

These all probably need looking at to see if the Microdata code can be optimised.

Next up:

https://schema.org/ItemList

Where are lists of products used;

- [x] https://github.com/gburton/Responsive-osCommerce/commit/3e201d66145bb70a81f4899917cecbec9c5186b6 index.php, new product for month module 
- [x] https://github.com/gburton/Responsive-osCommerce/commit/463b51f237122b63bd5fa5458be5705a340cbbee index->categories
- [x] https://github.com/gburton/Responsive-osCommerce/commit/8618be5203c1c85fff25bda705912da739d27f4f index->categories->lists of products 
- [x] https://github.com/gburton/Responsive-osCommerce/commit/8618be5203c1c85fff25bda705912da739d27f4f specials
- [x] https://github.com/gburton/Responsive-osCommerce/commit/8618be5203c1c85fff25bda705912da739d27f4f new_products
- [x] https://github.com/gburton/Responsive-osCommerce/commit/8618be5203c1c85fff25bda705912da739d27f4f advanced_search_result
- [x] https://github.com/gburton/Responsive-osCommerce/commit/40f4a98ca63ee440ae28930a6675daceef220498 best sellers box
- [x] https://github.com/gburton/Responsive-osCommerce/commit/0aea896616b5ba343675413068a4d124725612ae also purchased module

Can anyone think of anywhere else that lists are used (shop side, public facing)? Thanks

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/commit/3e201d66145bb70a81f4899917cecbec9c5186b6

This shows the ItemList for New Products Module...
Have tested via Googles Microdata Tester Tool and all seems well.

**Comment by Piernas** [comment]
There are list of reviews, but I imagine it's covered by reviews microdata??
There is the "also purchased" list.

**Comment by gburton** [comment]
Best Sellers Box

**Comment by BrockleyJohn** [comment]
advanced_search_result - another use of the product_listing module and probably somewhere that you want to keep crawlers out of anyway

**Comment by gburton** [comment]
All done and being tested, will pull in when testing is complete.
