### ISSUE TITLE
Photogrid enhancement

### ISSUE THREAD

**Issue by Piernas** [gburton/Responsive-osCommerce#345]
I've found an argument (gutter) in photogrid for to add spacing between thumbnail images in product_info. This eliminates the need of more complex CSS styling.
I think it could be easily added as an option in colorbox ht module. Do you think it's interesting?

Also the photogrid has been improved by adding optional border options to images some time ago, just in case you want to update the script, but there is no official release yet.

**Comment by gburton** [comment]
@Piernas 
Yes for the Gutter, thank you.
No for the Borders (until officially released).

**Comment by Piernas** [comment]
Let me clean up the border options ( already aded for my personal use) and I'll push the changes.
