### ISSUE TITLE
Super Globals and Session Variables

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#350]
The usage of long variables has been replaced with super globals...

$HTTP_GET_VARS -> $_GET

etc

**Comment by Piernas** [comment]
This involves almost all of the files. How do you want it to be done?

**Comment by gburton** [comment]
Yes, not sure.  Do you have a proposal?

**Comment by Piernas** [comment]
I'd do it all at once. The quickest way is using a search and replace util, except for a couple of files thas has to be done manually.

**Comment by gburton** [comment]
That commit would be too big.  Let me think on it.

**Comment by Piernas** [comment]
I think if it's done in one commit it will be less traumatic. Also, if other pending commits are reviewed there would be less conflicts to solve.

**Comment by gburton** [comment]
We'll wait until the PHP7 changes are finalised, then we'll go ahead and do a global S/R.
