### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Piernas** [gburton/Responsive-osCommerce#357]
When trying to install the latest edge files I'm receiving the following error on first page:

**Please enable Javascript in your browser to be able to start the installation procedure.**

This doesn't happen in previous downloaded files. Can someone confirm if it's a problem with install?

**Comment by Piernas** [comment]
My fault. Closed.

**Comment by Piernas** [comment]
Well finally it was a real issue. Jquery has not been updated on the install routine on install/templates/main_page.php and installation could not finish. Sometimes my browser was using a cached page (no idea why??) and worked, other times not...

**Comment by frankludriks** [comment]
Solution is right here as I had the same problem yesterday :-)

http://forums.oscommerce.com/topic/409355-installation-routines-for-modules/page-2#entry1742878
