### ISSUE TITLE
Want to give back

### ISSUE THREAD

**Issue by boelle** [gburton/Responsive-osCommerce#360]
as stated in http://forums.oscommerce.com/topic/409244-oscommerce-community-edition-get-involved/

i want to give something back... how is that best done?

**Comment by gburton** [comment]
Thanks Bo.  All of these things are specific to your particular shop, so would not be useful for the vast majority of shops.  

You can get involved in other ways such as testing New Code, answering questions on the Forum, getting involved in discussions and so on.

**Comment by boelle** [comment]
oki, what about danish language files? but i guess that one first comes after that the english ones have been cleaned up?

btw... there are romurs that you are making code so that adresses are checked against google?

**Comment by boelle** [comment]
hmmm 2nd thought.... the would a POS interface for oscommerce not be a welcomed feature?

i would imagine that people that have both a website and store front could use it

**Comment by gburton** [comment]
Not useful for the vast majority of shops.  If you want to make your POS an addon, please do.

**Comment by boelle** [comment]
dont know how to so i will kill that idea

are there any truth to what the forum have told me on that you are working on something that allows the address box'es to be autofilled from google maps?

**Comment by gburton** [comment]
https://www.youtube.com/watch?v=-fzMhPmQENA

**Comment by boelle** [comment]
yep what i had in mind... i assume it will also work with danish address system where streetname comes first

how do i get my dirty hands on this one?

**Comment by boelle** [comment]
is it a paid contribution?
