### ISSUE TITLE
Clean Install Bug sub total calculation (also in vanilla 2.3.4 from oscommerce.com)

### ISSUE THREAD

**Issue by SDGPeteBatin** [gburton/Responsive-osCommerce#364]
Hi,

I installed Edge in the hope you might have also experienced this bug and come up with a fix for it, looks like it hasn't been noticed before.

Thought it might be a good idea to post about it here as well as the forum in oscommerce.com in the hope that someone has a solution.

I'm looking for some help.

I've discovered a bug with order totals created by a mixture of includes/classes/currencies.php and includes/classes/order.php (and includes/classes/cart.php if viewing shopping_cart.php)

Consider the following GBP (default currency) basket (this is without any attributes or tax).

Product A: 22.99
Product B: 22.99
Product C: 26.99
Sub Total: 72.97

The above Sub Total without any currency conversion is correct.

Now changing currency to EURO with a currency value of 1.25 using the values above as base values to perform calculations.

1 x Product A: 28.74 EURO (22.99 x 1.25 = 28.7375 then passed to tep_round() = 28.74)
1 x Product B: 28.74 EURO (22.99 x 1.25 = 28.7375 then passed to tep_round() = 28.74)
1 x Product A: 33.74 EURO (26.99 x 1.25 = 33.7375 then passed to tep_round() = 33.74)
Displayed Sub Total: 91.21 EURO

The above Sub Total is incorrect when you add the Product Line Totals and should be 91.22 EURO

OSC calculates Sub Total by the following

(22.99 + 22.99 + 26.99) * 1.25 = 91.2125 then passes to tep_round() which rounds down to 91.21

Either the sub total calculation need to change by adding up the totals after conversion or the tep_round() function needs to change to stick with one method only, round up or round down.

Depending on the payment module and how relaxed the visitor to the website is about maths this may not matter much.  But when using the PayPal Pro Hosted module which actually charges the right amount the callback/IPN is rejected because of the 0.01 discrepancy.

**Comment by gburton** [comment]
Update to the latest Paypal App and re-test.

**Comment by SDGPeteBatin** [comment]
Hi,

The clean install test site doesn't have PayPal installed.  You only have to look at the cart to see the Sub Total is wrong by 0.01.

**Comment by gburton** [comment]
Update to the latest Paypal App and re-test.  
Latest Paypal App has some error checking in it.

Further response at the osCommerce Forum, thanks.
