### ISSUE TITLE
Multi-byte character encoding issue in Navbar Module -> Languages

### ISSUE THREAD

**Issue by Moxamint** [gburton/Responsive-osCommerce#365]
Languages with multi-byte characters such as Japanese & Chinese are scrambled when added to language files of Languages sub-module in Navbar Modules.  Japanese for example:

![image 1](https://cloud.githubusercontent.com/assets/11028615/15095323/bc17ea24-14f3-11e6-9168-018e497d9a62.png)

The scrambled characters "�饻�y" are supposed to be "日本語".  These characters display correctly elsewhere in my shop.

**Comment by gburton** [comment]
@Moxamint plase check your database tables are all UTF8 and that your language encoding is UTF8.  Report back your findings.

**Comment by Moxamint** [comment]
Thanks @gburton that does the trick.  I've been using PSPad as my editor and it told me that the encoding of all those language files were UTF-8.  Now I just checked again with Notepad ++ to find that those files were not really encoded correctly.  Guess I'll have to be more careful.

Thanks again.
