### ISSUE TITLE
https://www.youtube.com/watch?v=-fzMhPmQENA

### ISSUE THREAD

**Issue by boelle** [gburton/Responsive-osCommerce#369]
how do i get this on my BS/Responsive shop ?

**Comment by gburton** [comment]
Come on, this place is not for requests like this.

**Comment by boelle** [comment]
i tried to ask on another issue and got no clue on where and how to ask about it

**Comment by BrockleyJohn** [comment]
[http://forums.oscommerce.com/](url)
