### ISSUE TITLE
Password Functions

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#371]
PHPASS is used in osc 234 for Password Hashing.  I want to rip that out in favour of PHP's (since 5.5) inbuilt Password Functions.  More @ http://php.net/manual/en/book.password.php

tep_validate_password
-> password_verify

tep_validate_old_password
-> is unused in osc 234

tep_encrypt_password
-> password_hash

tep_encrypt_old_password
-> password_hash

tep_password_type
-> password_needs_rehash

Seems straightforward enough.

Anyone done it, anyone got **RELEVANT** comments.

**Comment by azpro-git** [comment]
@gburton relevant comment .. if your changes are onubstrusive in the sense old customers can still log in .. Well then no problem ...
I never really looked in to the code ... Don't know whether it's important at this stage of BS development.
Regards!

**Comment by jwisdom** [comment]
I think this is a great idea but I was unsure about old passwords.  From what I've read this is a much better/secure password system.

**Comment by jwisdom** [comment]
@gburton 
I have this working on the catalog side of my test site now with relatively little modification to the core files involved.  It upgrades old passwords in the same way the passwordhash file does.  I've only changed the following files.
password_funcs 
login 
cm_login_form

I haven't added the password_needs_rehash function in yet, but I'll work on that tomorrow.  After I tidy this up a little i'll post it.  There is also a compatible class that can be included for versions under php 5.5.  I think the passwordhash class file will need to stay to validate passwords based on it.

**Comment by gburton** [comment]
> After I tidy this up a little i'll post it

Yes please @jwisdom - thank you!

**Comment by jwisdom** [comment]
There's a little more for me to work on.  I need to modify the function to find password type.

**Comment by jwisdom** [comment]
Okay I created a pull request, but I'm not very good with git so let me know if I did it correctly.  We need to keep the class passwordhash in order to validate passwords hashed with it.  I've tested this and it will update old passwords to the new built in functions but I haven't added the password_needs_rehash function.  Going forward it seems best to have the tep_password_type function check for phpnative first but what do you think?  Not critical.  
Only 2 files needed updating.  

Let me know any thoughts and I'll probably post how to on the main forum.

**Comment by jwisdom** [comment]
One more thing.  The password field should be changed to VARCHAR(255) to be forward compatible according the php manual.
ALTER TABLE `customers` CHANGE `customers_password` `customers_password` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;

**Comment by gburton** [comment]
@jwisdom John, great thanks.  Will find time to test it as soon as I can.

**Comment by jwisdom** [comment]
If you have any questions or problems let me know, as I have played with this quite a bit and I have it running on my live site with no problems.  One thing is this is meant for php5.5 and higher, which I think you already know.  It can be run on 5.3.7 to 5.5 by including the library below, but people really should be 5.5 by now.
https://github.com/ircmaxell/password_compat/tree/master/lib

**Comment by gburton** [comment]
In readiness for 2.4, I'm not going to add any "big" changes to Responsive-osC.

Thank you for your hard work on this @jwisdom - appreciated.
