### ISSUE TITLE
Canonical on index pages

### ISSUE THREAD

**Issue by frankludriks** [gburton/Responsive-osCommerce#374]
No matter how many pages of products there are, canonical always points to first page.

If applicable should have page number in canonical, plus show prev/next canonical as well.

Proposed change from this 

`} elseif (basename($PHP_SELF) == FILENAME_DEFAULT) {
        if (isset($cPath) && tep_not_null($cPath)) {
          $oscTemplate->addBlock('<link rel="canonical" href="' . tep_href_link(FILENAME_DEFAULT, 'cPath=' . $cPath, 'NONSSL', false) . '" />' . "\n", $this->group);
        `

to

`if (isset($cPath) && tep_not_null($cPath)) {
		  if (isset($_GET['page']) && $_GET['page'] == '1') {
          $oscTemplate->addBlock('<link rel="canonical" href="' . tep_href_link(FILENAME_DEFAULT, 'cPath=' . $cPath, 'NONSSL', false) . '" />', $this->group);
		  $oscTemplate->addBlock('<link rel="next" href="' . tep_href_link(FILENAME_DEFAULT, 'cPath=' . $cPath . '&page=2', 'NONSSL', false) . '" />', $this->group);
		  } elseif (isset($_GET['page']) && $_GET['page'] != '1') {
			if (isset($_GET['page']) && $_GET['page'] == '2') {
			$oscTemplate->addBlock('<link rel="canonical" href="' . tep_href_link(FILENAME_DEFAULT, 'cPath=' . $cPath . '&page=' . $_GET['page'], 'NONSSL', false) . '" />' . "\n", $this->group);
			$oscTemplate->addBlock('<link rel="prev" href="' . tep_href_link(FILENAME_DEFAULT, 'cPath=' . $cPath, 'NONSSL', false) . '" />', $this->group);
			$oscTemplate->addBlock('<link rel="next" href="' . tep_href_link(FILENAME_DEFAULT, 'cPath=' . $cPath . '&page=' . ($_GET['page']+1), 'NONSSL', false) . '" />', $this->group);
			} else {
			$oscTemplate->addBlock('<link rel="canonical" href="' . tep_href_link(FILENAME_DEFAULT, 'cPath=' . $cPath . '&page=' . $_GET['page'], 'NONSSL', false) . '" />' . "\n", $this->group);
			$oscTemplate->addBlock('<link rel="prev" href="' . tep_href_link(FILENAME_DEFAULT, 'cPath=' . $cPath . '&page=' . ($_GET['page']-1), 'NONSSL', false) . '" />', $this->group);
			$oscTemplate->addBlock('<link rel="next" href="' . tep_href_link(FILENAME_DEFAULT, 'cPath=' . $cPath . '&page=' . ($_GET['page']+1), 'NONSSL', false) . '" />', $this->group);
			}
               } else {
		  $oscTemplate->addBlock('<link rel="canonical" href="' . tep_href_link(FILENAME_DEFAULT, 'cPath=' . $cPath, 'NONSSL', false) . '" />', $this->group);
		  $oscTemplate->addBlock('<link rel="next" href="' . tep_href_link(FILENAME_DEFAULT, 'cPath=' . $cPath . '&page=2', 'NONSSL', false) . '" />', $this->group);
		  }`

Reference: https://support.google.com/webmasters/answer/1663744?hl=en

**Comment by BrockleyJohn** [comment]
You seem to be conflating two separate concepts from the references with respect to paginated SEO: rel=canonical, if used, should point to a view all page if one exists, for every separate page. Alternatively, use rel=next/prev to link the series of pages and google will handle the rest.

rel=canonical is for duplicate content (such as the same product in more than one category) to define the version to index. There are two circumstances in which you might need rel=canonical for categories, neither of which apply:
- if you could have the same category in more than one place in the hierarchy, which you can't
- if you always had a session id on the end of the url, you could use rel=canonical to point to the category without session id

If the current core creates a rel=canonical pointing to the first page, that is wrong and it will result in only the first page being indexed. The best, quickest fix would be to take it out altogether and let google work it out for itself. A more complicated fix is to take out rel=canonical and put in rel=next/prev instead, but not both.

**Comment by frankludriks** [comment]
While I disagree that "There are two circumstances in which you might need rel=canonical for categories" - there is at least a third and possibly a fourth and fifth - I think it's best to remove it for now (or at the very least include page numbers in canonicals for categories where there is more than one page of products) too. 

As you say, the current core will only allow the first page of products to be indexed which is wrong.

**Comment by gburton** [comment]
If interested parties can come up with a consensus on the exact change(s) that need to be made, I'm happy to take an in-depth look...I don't know the absolute optimal setup for this...

As a person not involved in SEO in any way shape or form ... I think my preferred solution would be "KISS" (Keep It Stupidly Simple) - we add in the possibility to over-ride split_page_result something like "?page=all", and have this link as canonical.  

Thoughts?

**Comment by BrockleyJohn** [comment]
> we add in the possibility to over-ride split_page_result something like "?page=all", and have this link as canonical.

works for me

**Comment by frankludriks** [comment]
That is fine.

**Comment by gburton** [comment]
OK, let's do this next.  

If we were to use rel=prev and rel=next ... do those links have to be in the header of the site?  
Could we link them elsewhere (eg on the "Result Pages: << 1 | 2 | 3 >>" part of a split page)...

**Comment by gburton** [comment]
@frankludriks - just playing with the code you posted above at the moment...seems to work good.  I have 1 question that you can clear up...in your posted code, you link to the rel-next without checking if there needs to be a next link.  so if the end split page result is (say) page 3, you still link to a page 4.  At least that's what shows in my testing...

Q:
Is linking to a non-existant "next" unimportant?

**Comment by gburton** [comment]
Other option is as I posted above, a "view all" link.  This is the most simplest..I believe...and does all the pages that use product_listing in one shot ...

/includes/modules/product_listing.php

Find:
`$listing_split = new splitPageResults($listing_sql, MAX_DISPLAY_SEARCH_RESULTS, 'p.products_id');`

To:
```
$num_list = (isset($_GET['view']) && ($_GET['view'] == 'all') ) ? 999999 : MAX_DISPLAY_SEARCH_RESULTS; 
$listing_split = new splitPageResults($listing_sql, $num_list, 'p.products_id');
```

We then amend ht_canonical file to see if the URL has a _GET['page']  and if so, add in a link to the same php_self, but with a view=all parameter...

I'll come up with some workable code...for testing purposes.

**Comment by gburton** [comment]
In addition to code changes in post above...
http://pastebin.com/NGb8Z5ax (new execute function for ht_canonical)

Thoughts ?

**Comment by frankludriks** [comment]
The code I posted above does indeed add a phantom 'next' link where none exists. What would need to be done is count the number of products in a category and then divide by number of products displayed per page to get the exact number of pages. I never did that because on Bing and Google people search for our products rather than our product categories (slack I know!).

The rel=next and rel-prev tags need to go in the head section of the page.

I made the changes to product listing module above and the changed the execute function from the pastebin link above and received this error:

`Parse error: syntax error, unexpected '[' in /home/myhouse/public_html/edge/includes/modules/header_tags/ht_canonical.php on line 86`

Technically the 'view_all' page is the best solution except perhaps for some stores with thousands (hundreds?) of products in each category.

**Comment by BrockleyJohn** [comment]
For index, perhaps it's the manufacturer view all page that might give the bigger problems and over which the store owner has no control. I wonder how many products Corinne has from one manufacturer. The google rep in the video reckoned that google is pretty good at consolidating paged content without any help, so an option to turn it off for the products depth index page would do no harm... 

Adding view all to advanced search result seems like a big risk to live stores unless there's a limit on the number of results returned. However, thinking it through, there are fewer queries than in the paginated version. The issue only arises if the store has implemented one of those dodgy addons that runs a query for each product returned.

Specials I would guess is less of an issue.

**Comment by gburton** [comment]
> The rel=next and rel-prev tags need to go in the head section of the page.

Too much complication to go forward with this - it would need a SQL call and a lot of logic to get something that should be simple :(

View = all is the way to go.

**Comment by gburton** [comment]
> Adding view all to advanced search result seems like a big risk to live stores unless there's a limit on the number of results returned.

We can just not have a canonical for advanced_search_result ?  
Let's limit it to index, specials and products_new.  Thoughts ?

**Comment by gburton** [comment]
> Parse error: syntax error, unexpected '[' in /home/myhouse/public_html/edge/includes/modules/header_tags/ht_canonical.php on line 86

Hmmm, my ht_canonical has a total of only 71 lines of code...after the new execute is in place of the original...

**Comment by gburton** [comment]
> I wonder how many products Corinne has from one manufacturer.

If it works for 95% of shops, that's good enough.

**Comment by frankludriks** [comment]
> Hmmm, my ht_canonical has a total of only 71 lines of code...

Sorry I had a bunch of commented lines. The line in question is 

`$view_all_pages = ( defined('MODULE_HEADER_TAGS_GRID_LIST_VIEW_PAGES') && tep_not_null(MODULE_HEADER_TAGS_GRID_LIST_VIEW_PAGES) ) ? array_diff(explode(';', MODULE_HEADER_TAGS_GRID_LIST_VIEW_PAGES), ['index.php']) : array('advanced_search_result.php', 'products_new.php', 'specials.php');`

> View = all is the way to go.

> Let's limit it to index, specials and products_new.

Agreed.

**Comment by gburton** [comment]
I suspect you are on php < 5.4 ... so [] for an array won't work for you...

Change it to:
$view_all_pages = array('products_new.php', 'specials.php');

That will then only show on these two pages, as well as index.php which is taken care of earlier in the code.  Let me know how it goes?

**Comment by frankludriks** [comment]
Actually 5.3.29, but upgrading tonight so will test tomorrow.

**Comment by frankludriks** [comment]
Tested and works fine.

I was thinking perhaps that something like $oscTemplate->addBlock('<link rel="prev" />' . "\n", 'header_tags'); could be added to the relevant sections in functions/classes/split_page_results.php. I tried it but it didn't work, no error but just didn't add a header tag to the page. I'm not clever enough to work that out.

**Comment by gburton** [comment]
@frankludriks I tried to do somehting in the split_page_results class, but failed miserably.
I'll drag together the code changes into a Branch to make for easier testing.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/pull/384
should do it.  This needs mega-testing prior to inclusion into Core...

**Comment by skleiner** [comment]
@gburton @frankludriks 
On a uniserver shop...products new shows this on the various pages:

<link rel="canonical" href="http://localhost/Responsive-osCommerce-master/products_new.php?view=all" />

For manufacturers, Canon, all pages shows this:

link rel="canonical" href="http://localhost/Responsive-osCommerce-master/index.php?view=all&amp;manufacturers_id=3"

For specials.php the test shop just has one page and it shows this:

<link rel="canonical" href="http://localhost/Responsive-osCommerce-master/specials.php?view=all" />

For first level category such as http://localhost/Responsive-osCommerce-master/index.php?cPath=1 I don't see a canonical

For second level category such as http://localhost/Responsive-osCommerce-master/index.php?cPath=1_17 I see ;
<link rel="canonical" href="http://localhost/Responsive-osCommerce-master/index.php?view=all&amp;cPath=1_17" />

**Comment by gburton** [comment]
All looks good, thanks for testing @skleiner 

> For first level category such as http://localhost/Responsive-osCommerce-master/index.php?cPath=1 I don't see a canonical

There are no products in a category that has subcategories, so no canonical is needed.

**Comment by skleiner** [comment]
Testing this on a live shop with a SEO url add on, for categories I see:

> www.shopname.com/first-level-category-c-291.html
No Canonical

www.shopname.com/secon-level-catetory-c-291_292.html
No Canonical

www.shopname.com/third-level-category-c-291_292_293.html

link rel="canonical" href="http://www.shopname.com/third-level-category-c-291_292_293.html?view=all" />

**Comment by gburton** [comment]
@skleiner in my opinion, looks good....other opinions invited

291 => only has subcat(s) => no pagination => view=all not needed
292 => only has subcat(s) => no pagination => view=all not needed
293 => has products => potentially has pagination => view=all shows 
1118 => shows canonical (with no parameters, eg attributes)
