### ISSUE TITLE
Edge Browser

### ISSUE THREAD

**Issue by Danta67** [gburton/Responsive-osCommerce#395]
Hi there,

I think there is an isue with the edge browser from win 10
Problem is that none of the form can be filled with data
Check create account and its not possible to fill in the fields

Danny

**Comment by gburton** [comment]
Cannot replicate on http://template.me.uk/234bs3/create_account.php
W10, Edge 25.10586.0.0

**Comment by Danta67** [comment]
Strange its a clean osc version so dont understand why it doesnt work for me

**Comment by Danta67** [comment]
Sorry i just tryed it again and everythig works 

please close this
