### ISSUE TITLE
Modular "Contact us"

### ISSUE THREAD

**Issue by katapofatico** [gburton/Responsive-osCommerce#397]
Hello,
In my business I have to make modular "Contact us". Are you interested on it? @gburton

**Comment by katapofatico** [comment]
I have it ready here:
https://github.com/katapofatico/Responsive-osCommerce/tree/Modular-Contact-Us

**Comment by gburton** [comment]
@katapofatico great thank you.  I have another version here (sent to me by someone else).  I will compare the two versions (yours and his), and take some of each into a modularised contact page.

Thanks!
