### ISSUE TITLE
login.php

### ISSUE THREAD

**Issue by 143books** [gburton/Responsive-osCommerce#401]
When selecting a returning customer the panels for customer input do not show what information is being asked for:

a name, account number or email,  it is unclear to a new returning user.

A label needs to be added to the fields.

Ta

**Comment by gburton** [comment]
@143books you can add labels if you wish.  You could also set placeholders for those boxes, amend these two lines to add in some text;

https://github.com/gburton/Responsive-osCommerce/blob/master/includes/languages/english.php#L98
and
https://github.com/gburton/Responsive-osCommerce/blob/master/includes/languages/english.php#L130
