### ISSUE TITLE
"Grid" or "List" how to change to use only "List" or "Grid"

### ISSUE THREAD

**Issue by jcerutti** [gburton/Responsive-osCommerce#412]
Hello everyone, i can't find any easy way to set the default product listing 
now the default setting is "Grid" and i want to use "List" as default.
but where to change that without changing a lot of code??
![grid](https://cloud.githubusercontent.com/assets/20859048/17436494/c1746ea8-5aed-11e6-9e81-a40194ec1cde.png)

SOLVED

**Comment by gburton** [comment]
Solved.  Apparently.
