### ISSUE TITLE
Placeholder(s) in Login

### ISSUE THREAD

**Issue by ArtcoInc** [gburton/Responsive-osCommerce#413]
In /includes/languages/english.php, you have the following definitions:

define('ENTRY_EMAIL_ADDRESS', 'E-Mail Address');
define('ENTRY_EMAIL_ADDRESS_TEXT', '');

-and- 

define('ENTRY_PASSWORD', 'Password');
define('ENTRY_PASSWORD_TEXT', '');

In /includes.modules/content/login/templates/login_form.php, you call the defined entries ENTRY_EMAIL_ADDRESS_TEXT and ENTRY_PASSWORD_TEXT as placeholders for the entry fields. Both of these are blank, leaving no placeholders showing in the entry fields.

May I ask why you have two definitions that, as far as I can see, are only used to create empty placeholders, where the inclusion of the placeholders would be useful?

**Comment by gburton** [comment]
See https://github.com/gburton/Responsive-osCommerce/issues/401

Shopowners are expected to insert their own words.

ENTRY_PASSWORD = label
ENTRY_PASSWORD_TEXT = placeholder

**Comment by auzStar** [comment]
The issue is that there is no label either for the login box, see attached. 

![login_fields](https://cloud.githubusercontent.com/assets/12169882/18295407/6c8c5ba6-74e4-11e6-8abe-764848acfd9b.jpg)
