### ISSUE TITLE
urlencoding illegal/not recommended parameters

### ISSUE THREAD

**Issue by ShaGGyUK** [gburton/Responsive-osCommerce#417]
#Items containing Attributes pass {x} in URL this is not advised 

see http://stackoverflow.com/questions/23064605/when-if-ever-should-characters-like-and-curly-braces-be-percent-encoded

{ & } are blocked on my host I-Page and maybe others.

suggest urlencoding from core level to prevent host incompatibility in the future.

**Comment by gburton** [comment]
The whole attributes system will be receiving attention at some point in the future.

In the meantime, if anyone else has similar issues, they can refer to your link.

Thanks
