### ISSUE TITLE
Idea.... Version checker

### ISSUE THREAD

**Issue by boelle** [gburton/Responsive-osCommerce#423]
While going through all the admin langauge files i had an idea

could the version checker not be used to say if there are an update to Edge? or Gold for that matter?

of course it would require edit of the version file for each update...

but for us that runs edge it would be a simple way to check if everything is updated

**Comment by gburton** [comment]
Version Checker is due to be removed in favour of Online Updates.

**Comment by boelle** [comment]
oki... how will that work together with a modded install?
