### ISSUE TITLE
\admin\includes\classes\payment.php & \admin\includes\classes\shipping.php

### ISSUE THREAD

**Issue by boelle** [gburton/Responsive-osCommerce#424]
The install guide for the module from my payment provider says to edit those

But i can see they are gone...

Have they moved somewhere else and got a new name or what will i have to do here?

**Comment by gburton** [comment]
These classes have never existed in osCommerce admin.

For third party modules "The install guide for the module from my payment provider says to edit", use forums.oscommerce.com

**Comment by boelle** [comment]
you are right.... i have mistaken them for 

admin/includes/classes/order.php
admin/includes/classes/currencies.php

**Comment by boelle** [comment]
ahh... the files come from the ship2pay module
