### ISSUE TITLE
\admin\includes\modules\security_check\ & \admin\includes\modules\newsletters\ & \admin\includes\modules\dashboard\ & \includes\modules\cfg_modules\ & \admin\includes\classes\

### ISSUE THREAD

**Issue by boelle** [gburton/Responsive-osCommerce#425]
all modules in here are not updated to php7 in the way most other things are..

is this on purpose or have we just not come that far yet?

\admin\includes\classes\ only a few files in here can be exluded.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/issues/288 for all php7 related discussion
