### ISSUE TITLE
 includes/application_top.php    after your last edit as at 07.09.2016

### ISSUE THREAD

**Issue by 143books** [gburton/Responsive-osCommerce#432]
PHP Warning:  require(DIR_WS_FUNCTIONSdatabase.php): failed to open stream: No such file or directory in /www/includes/application_top.php on line 61, referer: http://www.#######.com/install/install.php?step=4
PHP Fatal error:  require(): Failed opening required 'DIR_WS_FUNCTIONSdatabase.php' (include_path='.:/usr/share/php:/usr/share/pear') in /www/includes/application_top.php on line 61, referer: http://www.######.com/install/install.php?step=4
PHP Warning:  require(DIR_WS_FUNCTIONSdatabase.php): failed to open stream: No such file or directory in /www/includes/application_top.php on line 61
 PHP Fatal error:  require(): Failed opening required 'DIR_WS_FUNCTIONSdatabase.php' (include_path='.:/usr/share/php:/usr/share/pear') in www/includes/application_top.php on line 61
 PHP Warning:  require(DIR_WS_FUNCTIONSdatabase.php): failed to open stream: No such file or directory in /www/includes/application_top.php on line 61
PHP Fatal error:  require(): Failed opening required 'DIR_WS_FUNCTIONSdatabase.php' (include_path='.:/usr/share/php:/usr/share/pear') in /www/includes/application_top.php on line 61

**Comment by 143books** [comment]
Ignore the mysqli_connect() line, my password was wrong there. But the other lines need to change.

**Comment by 143books** [comment]
'includes/functions/

also admin/application_top.php

lots of DIR_WS_FUNCTIONS in both file relating to this edit.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/commit/8e21497bad17c66554ab04c7feff35844313358e
