### ISSUE TITLE
DIR_WS_FUNCTIONS not replaced with hard code path

### ISSUE THREAD

**Issue by Moxamint** [gburton/Responsive-osCommerce#433]
In the last merge from pull request #420, there are quite a few DIR_WS_FUNCTIONS in 'includes\application_top.php' were not properly replaced by the hard code path.

**Comment by boelle** [comment]
have a look at this one :-D

https://github.com/gburton/Responsive-osCommerce/issues/432

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/commit/8e21497bad17c66554ab04c7feff35844313358e

**Comment by boelle** [comment]
maybe have a look at https://github.com/gburton/Responsive-osCommerce/issues/288 while at it?

**Comment by gburton** [comment]
No thanks.  Do not post unrelated to topics.
