### ISSUE TITLE
Cannot see Admin page after install

### ISSUE THREAD

**Issue by 143books** [gburton/Responsive-osCommerce#435]
PHP Warning:  require(DIR_WS_FUNCTIONScompatibility.php): failed to open stream: No such file or directory in www/admin/includes/application_top.php on line 35, referer: http://www.blahblah.com/install/install.php?step=4

 PHP Fatal error:  require(): Failed opening required 'DIR_WS_FUNCTIONScompatibility.php' (include_path='.:/usr/share/php:/usr/share/pear') in /www/admin/includes/application_top.php on line 35, referer: http://www.blahblah.com.au/install/install.php?step=4

more errors:-

 'includes/classes/  in application_top.php

and in password_funcs.php
password_funcs.php

'DIR_WS_MODULESdashboard/d_total_revenue.php' in /www/admin/index.php 

include(DIR_WS_MODULES . 'dashboard/' . $class . '.php');

admin/includes/modules/dashboard/d_latest_news.php

/admin/categories.php on line 15
/admin/currencies.php
/aadmin/orders.php
/admin/stats_customers.php

**Comment by BrockleyJohn** [comment]
The admin side isn't done yet (for DIR_WS_FUNCTIONS at least) - did the install create an admin config that doesn't have the constant(s) set properly?

**Comment by 143books** [comment]
Yes sorry to push but Im re-installing a fresh so the admin side was
important to me. Ive just found an old copy from 26.06.2016 so Im
installing that now to get my site back up.

Maybe so things still work off the bat (so to speak) you might leave the
DIR_WS_ definitions in place until your sure everything is fine so that
anyone installing from the GIT it would appear OK and the changes could
then be gradual.

I'm sorry I don't know too much PHP just what I'm learning from your
changes and the plugins that I'm trying to install.


Thanks this is a great product and when things work out of the box that's
a good thing as I talk to a lot of people and they are keen to host there
own shops.

I will donate for all your work a bit later, my physical shop is not going
to well at the moment but x-mass comes soon :)

Thanks mate.

**Comment by gburton** [comment]
Things are done as and when I get time, if something is broken, it stays broken until I get around to it.   Do not use Edge if you do not know how to fix/change things.
