### ISSUE TITLE
small error in breadcrumb code in application_top

### ISSUE THREAD

**Issue by raiwa** [gburton/Responsive-osCommerce#445]
If the following settings are used:
Admin => Modules => Header Tags => Product Title => SEO Breadcrumb Override? => set to "true"
and
if the SEO Product Title in categories/edit product is left blank.
the model is still used in the product breadcrumb => should be name
Fix:
in: aplication_top.php line 510 change p.products_model to pd.products_name
`      $model_query = tep_db_query("select coalesce(NULLIF(pd.products_seo_title, ''), pd.products_name) as products_model from products p, products_description pd where p.products_id = '" . (int)$_GET['products_id'] . "' and p.products_id = pd.products_id and pd.language_id = '" . (int)$languages_id . "'");
`

tested with edge version fom 2016/09_10

rgds
Rainer

**Comment by gburton** [comment]
If SEO breadcrumb over-ride is set to true and the shopowner has inserted nothing into the seo product title, the title shows blank.  This is as it should be.

**Comment by raiwa** [comment]
It doesn’t show blank in the breadcrumb, it shows the product model and this is what is said in categories.php edit product:

 

Products Title for SEO:
Replaces the product name in the <title> Meta Element
and optionally in the Breadcrumb Trail.
Leave blank to default to product name.

 

De: gburton [mailto:notifications@github.com] 
Enviado el: jueves, 29 de septiembre de 2016 17:16
Para: gburton/Responsive-osCommerce
CC: Rainer Schmied; Author
Asunto: Re: [gburton/Responsive-osCommerce] small error in breadcrumb code in application_top (#445)

 

If SEO breadcrumb over-ride is set to true and the shopowner has inserted nothing into the seo product title, the title shows blank. This is as it should be.

**Comment by gburton** [comment]
Yes, that is correct.  Again, as far as I recall:

if the seo override is TRUE, and the seo_title is NULL ... model shows
if the seo override is TRUE and seo_title is blank ... blank shows

As intended.

**Comment by raiwa** [comment]
Sorry, i understand her:

Products Title for SEO:
Replaces the product name in the <title> Meta Element
and optionally in the Breadcrumb Trail.
Leave blank to default to product name.

if the seo override is TRUE

and seo_title is blank or null product name shows

 

De: gburton [mailto:notifications@github.com] 
Enviado el: jueves, 29 de septiembre de 2016 18:11
Para: gburton/Responsive-osCommerce
CC: Rainer Schmied; Author
Asunto: Re: [gburton/Responsive-osCommerce] small error in breadcrumb code in application_top (#445)

 

Yes, that is correct. Again, as far as I recall:

if the seo override is TRUE, and the seo_title is NULL ... model shows
if the seo override is TRUE and seo_title is blank ... blank shows

As intended.

**Comment by gburton** [comment]
So the english is not so good.  Again so far as I recall;

if the seo override is TRUE, and the seo_title is NULL ... model shows
if the seo override is TRUE and seo_title is blank ... blank shows
if the seo override is TRUE and seo_title is filled in ... seo title shows <-- that is the only case where an override occurs.

I don't have anymore time for this right now, so consider this closed.
