### ISSUE TITLE
Equal Height Deprecation (other files)

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#446]
Equal Height deprecation has resolved the problems in the product_listing module.

There are other places where lists of products occur that need to be aligned, eg 
the "new products for month" modules in index.php and the nested index.php
also_purchased module

As shopowners come across such product groups, please report them here so that a commit can be made to solve the uneven display.  

Thanks

**Comment by gburton** [comment]
New Products for Month (index and index nested) needs attention

**Comment by BrockleyJohn** [comment]
Did them along with also purchased products. Shouldn't it be a product info content module?

**Comment by BrockleyJohn** [comment]
Incidentally, categories exhibit the same problem: see [http://bromleybr.co.uk/bsgit/index.php?cPath=1](example)

**Comment by gburton** [comment]
TY @BrockleyJohn
