### ISSUE TITLE
Structured data  in module also_purchased_products.php

### ISSUE THREAD

**Issue by azpro-git** [gburton/Responsive-osCommerce#451]
http://template.me.uk/234bs3/product_info.php?products_id=28 for also purchased Google test tool:

https://search.google.com/structured-data/testing-tool#url=http%3A%2F%2Ftemplate.me.uk%2F234bs3%2Fproduct_info.php%3Fproducts_id%3D28

Gives an error:
ItemListElement
	
SWAT 3: Close Quarters Battle (Must have Value  in field position.)

**Comment by gburton** [comment]
http://pastebin.com/Y5cNHqEK

Please test, thanks

**Comment by azpro-git** [comment]
Tested! Looks fine now!

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/pull/453
