### ISSUE TITLE
PayPal Standard - Incorrect Redirect Link After Process

### ISSUE THREAD

**Issue by Moxamint** [gburton/Responsive-osCommerce#456]
`\includes\modules\payment\paypal_standard.php`

Redirect link after process is:
`tep_redirect(tep_href_link('checkout_process.php', '', 'SSL'));`

Which instead should be:
`tep_redirect(tep_href_link('checkout_success.php', '', 'SSL'));`

**Comment by gburton** [comment]
> Redirect link after process is:
> tep_redirect(tep_href_link('checkout_process.php', '', 'SSL'));

is correct...

**Comment by raiwa** [comment]
It seems this is an error which has been introduced with the PayPal App and changing the filename constants to hardcoded filenames.
In all other versions checkout_success.php is used in that place, not checkout_process.php

All older paypal standard versions from osc 2.2 to 2.3.4BS before PayPal App integration:
`      $this->after_process();
............
      tep_redirect(tep_href_link('checkout_success.php', '', 'SSL'));
`
or
`
      tep_redirect(tep_href_link(FILENAME_CHECKOUT_SUCCESS, '', 'SSL'));
`
osc 2.4:
`    function after_process() {
...............................
      OSCOM::redirect('checkout_success.php');
`

Osc2.3.4 BS after PayPal App integration:
`    function after_process() {
....................................
      tep_redirect(tep_href_link('checkout_process.php', '', 'SSL'));
`
