### ISSUE TITLE
Warning in product_rewiews.php

### ISSUE THREAD

**Issue by marcochiana** [gburton/Responsive-osCommerce#461]
I had this message if I try to write a rewiew
Warning: Illegal string offset 'type' in C:\xampp5519\htdocs\oscommercebs\includes\functions\html_output.php on line 350

Warning: Illegal string offset 'type' in C:\xampp5519\htdocs\oscommercebs\includes\functions\html_output.php on line 353

Warning: Illegal string offset 'type' in C:\xampp5519\htdocs\oscommercebs\includes\functions\html_output.php on line 354

Warning: Illegal string offset 'type' in C:\xampp5519\htdocs\oscommercebs\includes\functions\html_output.php on line 357

Warning: Illegal string offset 'type' in C:\xampp5519\htdocs\oscommercebs\includes\functions\html_output.php on line 367

Warning: Illegal string offset 'type' in C:\xampp5519\htdocs\oscommercebs\includes\functions\html_output.php on line 375

Warning: Illegal string offset 'type' in C:\xampp5519\htdocs\oscommercebs\includes\functions\html_output.php on line 394

the problems seems in this line in product_review.php
`    <p><?php echo tep_draw_button(IMAGE_BUTTON_IN_CART, 'fa fa-shopping-cart', tep_href_link($PHP_SELF, tep_get_all_get_params(array('action')) . 'action=buy_now'), null, 'btn-success btn-reviews btn-buy'); ?></p>`
I solved in this way 
`
    <p><?php echo tep_draw_button(IMAGE_BUTTON_IN_CART, 'fa fa-shopping-cart', tep_href_link($PHP_SELF, tep_get_all_get_params(array('action')) . 'action=buy_now'), null); ?></p>
`
But i'm not sure this affect something in the store

**Comment by gburton** [comment]
No osCommerce version.
