### ISSUE TITLE
jquery 3

### ISSUE THREAD

**Issue by MyBookShop** [gburton/Responsive-osCommerce#464]
After update the Cart and the Account in the top banner do not work it returns to the main page www.whaterver.com/#

Console shows:
Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

The issue is discussed here https://github.com/twbs/bootstrap/issues/16834

Do you have this problem or is it just me?

I will return prior Jquery.

**Comment by gburton** [comment]
I wasn't able to recreate this.  All works well...

Make sure that you have bootstrap 3.3.7 as this version was updated to deal with the changes in jQuery3.

**Comment by MyBookShop** [comment]
Thankyou will try these versions together.
