### ISSUE TITLE
PayPal App login module template

### ISSUE THREAD

**Issue by raiwa** [gburton/Responsive-osCommerce#469]
The PayPal Login module template is the wrong version from 2.3.4 standard.

rgds
Rainer

PS: Sorry, can't open a pull request, my repository is complete outdated. Will try to update but no time for now.

**Comment by raiwa** [comment]
OK, I created finally a new clean repository and opened a pull request for this issue.

rgds
Rainer

**Comment by gburton** [comment]
TY.

**Comment by gburton** [comment]
TY.

https://github.com/gburton/Responsive-osCommerce/commit/8bb457312e04c73229957a49054f0bb24fc7d0e9
