### ISSUE TITLE
Store Pickup with Flat rate.

### ISSUE THREAD

**Issue by MyBookShop** [gburton/Responsive-osCommerce#472]
It would appear a small logic error allows free shipping in two cases.

I have two shipping options: Flat and Store Pickup.

I have enabled external shipping rate in Paypal.

A default checkbox is automatically selected when checking out. If the customer does not select an option by actually highlighting by selecting by turning the option green *and* it happens to be the Flat rate the postage is not passed on to Paypal, free postage!!

I have re-ordered these two delivery options and set default postage rates to in my Paypal setup. (Update: Setting rates in Paypal did not help, I suggest its passing a zero amount for shipping and not using defaults.)

I see from many shipping forum posts that this could be a contributor to some confusion.

Solution: no default check box setting, forcing client to select an option. 

However this does not fix it in the Express Checkout option (which appears the page before the shipping option) where the client has not selected a postage option prior to clicking on the express checkout button. (the option is never given if express checkout is selected but my testing shows if you cancel and go back to the cart and then select express checkout the postage option is then remembered.)

Solution: is to move the express checkout button onto the postage page and not allow until a postage option is selected.

Some background.
http://forums.oscommerce.com/topic/365297-shipping-cost-not-showing-on-pay-pal/

**Comment by gburton** [comment]
Can you be clearer about what you feel is not working as it should be?

Paypal App?
Bootstrap Implementation?
Javascript?
Lack of required attribute on a form?

I really have no clue based on your comments above.
Thanks

**Comment by MyBookShop** [comment]
Sure.
On a clean browser.
If I select any product, and add it to the cart, then choose [checkout with paypal] , no postage is passed onto paypal. 

Thats it.

**Comment by MyBookShop** [comment]
This is actually a .real. problem with OSC.!

I removed these lines from shopping_cart.php

    if (!empty($initialize_checkout_methods)) {
?>
  <div class="clearfix"></div>
  <p class="text-right"><?php echo TEXT_ALTERNATIVE_CHECKOUT_METHODS; ?></p>

<?php
      reset($initialize_checkout_methods);
      while (list(, $value) = each($initialize_checkout_methods)) {
?>

  <p class="text-right"><?php echo $value; ?></p>

<?php
      }
    }

This got rid of the express button from the page and now flows throu the shipping options for calculation of shipping rates.

**Comment by MyBookShop** [comment]
This is actually a .real. problem with OSC.

My Solution for my site, which has only one payment provider Paypal to
progress to after going throu the shipping options.
[Disabling the express checkout in Admin also disabled checking out with
Paypal]

I removed these 15 lines from shopping_cart.php to disable Paypal Express
Checkout from this page.

    if (!empty($initialize_checkout_methods)) {
?>
  <div class="clearfix"></div>
  <p class="text-right"><?php echo TEXT_ALTERNATIVE_CHECKOUT_METHODS; ?></p>

<?php
      reset($initialize_checkout_methods);
      while (list(, $value) = each($initialize_checkout_methods)) {
?>

  <p class="text-right"><?php echo $value; ?></p>

<?php
      }
    }

This got rid of the express button from the page and now flows throu to
the shipping options for calculation of shipping rates before flowing onto
Paypal payments.

As I only have 1 payment option Paypal this [hack] fits my store. If two
or more options were available then this would probably not be suitable.

I hope that you can see what I'm getting at now?

(Maybe the problem lies in the store setup options somewhere but Its not
obvious.)

**Comment by MyBookShop** [comment]
in checkout_shipping2

so despite its default in line  292     $checked
if its not cliked on
its never                      table-selection success
but we are allowed to move on and postage is not calcutaled.

I'm sorry for the limited explaination, I'm no coder thats for sure.

**Comment by MyBookShop** [comment]
I spent a little time inspecting elements in my browser.

in checkout_shipping2

so despite its default in line  292     $checked
if its not clicked on
its never                      table-selection success
in jquery.
But we are allowed to move on to the next page and postage is not calculated.

I'm sorry for the limited explanation, I'm no coder that's for sure.

**Comment by gburton** [comment]
I am not certain, but I think you need to turn on "instant updates" which allows Paypal Express to get shipping methods from your shop on a live and as needed basis.  See https://library.oscommerce.com/Package&en&paypal&oscom23&express_checkout

> Instant Update
> 
> As soon as the customer has logged in at PayPal or has provided their shipping address during the Express Checkout flow, PayPal contacts your online store to retrieve a list of applicable shipping rates and taxes for the shipping destination. The customer is able to choose their preferred shipping rate which is passed back to the store to use for the order.
> 
> As of osCommerce Online Merchant v2.3.4, orders can be blocked when no shipping rate for the destination is available. If this is enabled and Instant Update detects that no shipping rates are available, it requests the customer to select or enter a new shipping address during the Express Checkout flow and prevents them to continue with the order until a valid shipping destination has been selected.
> 
> Requirements
> 
> Instant Update requires the following for the shipping rates to be retrieved:
> 
> Your store installation must be configured for and have SSL enabled.

**Comment by MyBookShop** [comment]
Thanks its always the blindingly obvious that you miss.

I have enables the option. Its a long time between sales so guess I will
have to wait until then to see.

As soon as im on top of my rent Ill send ya some more $$ or ##.

Also:

For your plugin page or the admin panel, maybe a way to reset all product
views to 0 and display the date all last cleared.
This would help my store a little.


Anyway thanks for the help.

Mark.
