### ISSUE TITLE
Spanish Language Pack

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#480]
https://github.com/gburton/Responsive-osCommerce/tree/Espanol

Any native Spanish speakers, please help out with any translations. Thank You.
This branch will be kept up to date with any language changes made in the main Repo.

@katapofatico @raiwa @piernas 

**Admin Side**
- [x] modules/boxes/
- [x] modules/cfg_modules/
- [x] modules/dashboards/
- [x] modules/newsletters/
- [x] modules/security_check/
- [x] remove unused buttons
- [x] main language files A thru D
- [x] main language files G thru P
- [x] main language files R thru Z
- [x] main espanol language file

**Shop Side**
- [ ] Paypal App
- [x] modules/action_recorder/
- [x] modules/boxes/
- [x] modules/content/  <--- big job, see to-do list below
- [x] modules/header_tags/
- [x] modules/navbar_modules/
- [x] modules/order_total/
- [ ] modules/payment/
- [x] modules/shipping/
- [x] modules/social_bookmarks/
- [x] change icon
- [x] main language files A thru C
- [x] main language files D thru T
- [x] main espanol language file

**modules/content/**
- [x] account/
- [x] checkout_success/
- [x] footer/
- [x] footer_suffix/
- [x] header/
- [x] index/
- [x] index_nested/
- [x] login/
- [x] navigation/
- [x] product_info/

**Comment by Piernas** [comment]
Fine. I'll start with admin.
In the process we may find some unused constants. How should we act with them?

**Comment by Piernas** [comment]
I see @raiwa already uploaded the files. Anyway I double-checked main admin file and found some accents and non-spanish words.
Is it okay to push into master? I'm receiving a 403 error when trying to do >git push origin Espanol

**Comment by Piernas** [comment]
@gburton I've created a pull request manually by editing the file on the web. What is the correct command to create this from git?

**Comment by raiwa** [comment]
@Piernas I think you should submit your corrections to my repository.
There are also many of the payment modules left for translation.

**Comment by gburton** [comment]
TY @Piernas.  
This will always be a branch @Raiwa - your files are helpful, TY.

**Comment by Piernas** [comment]
@raiwa I'll do. Will review the files one by one.

**Comment by gburton** [comment]
Admin Side fully complete, thank you to all.

**Comment by gburton** [comment]
OK guys, I need some Spanish help on the following areas;

- Paypal App
- modules/content/index & index_nested
- moduls/payment (all)

Thanks

**Comment by katapofatico** [comment]
I have created pull requests with modules/content/index translated

**Comment by katapofatico** [comment]
.. and index_nested too. I'm sorry because my too much granular commits: I don't have my IDE: I'm editing with github editor

**Comment by gburton** [comment]
@katapofatico thank you!

**Comment by BrockleyJohn** [comment]
When I use the Espanol branch to add the language to a test store, it removes all the English language files. Presumably a commit somewhere contains deletes for English language files. Surely that's not what was intended? I'm afraid it probably needs the branch rebuilding.

**Comment by gburton** [comment]
This would be used by making a zip of the branch, downloading and then installing into live-shop.

**Comment by BrockleyJohn** [comment]
ok got it now

**Comment by gburton** [comment]
It might be that after the translates are all complete and done...we make a zip and instead up it to the addons area (for ease of use).  And just keep this as a repository for easy changes.

**Comment by Piernas** [comment]
Could you please consider to add it to the main branch?
@raiwa already mantains a translation on guthub and as an addon on the downloads section. 
Having the chance to set it up directly would be much more attractive for spanish shopowners as not everyone in Spain or Latin America knows enough english to dig on the general forums to learn how to install it, and I presume it's probably the second language in number of oscommerce shops installed. It would boost interest inside spanish community for sure.

Another good reason is the main sections in admin are not translated; I had to translate some sections in the past for non english speaking shopowners that coldn't figure out what some areas mean. I can add the database translations, too (if you wish) for sample products and general options, and even for other parts if you want.

And I am committed to translate changes as they happen (anyway it's not too much work and I'll do it for me).

**Comment by gburton** [comment]
Raiwa's translation is missing lots of translates, has lots of translates that don't exsit in the english languaeg files (eg changed core code, addons and so on).  That is why this branch exists, so that you and others can add/amend to raiwa's work...

**Comment by gburton** [comment]
Could any of you guys working on this, update me as to status?
Thanks chaps!

**Comment by Piernas** [comment]
I stopped working on it to avoid overlapping work. Will have a look and see what's missing.

**Comment by gburton** [comment]
Abandoned.

**Comment by iosebah** [comment]
Greetings,

I'm working with these files this days, if you want, I can check them. Just tell me what files or folders.

(Basque, Catalan, Spanish and English knowledges)

Keep in touch, Joseba.
