### ISSUE TITLE
Danish Language?

### ISSUE THREAD

**Issue by boelle** [gburton/Responsive-osCommerce#487]
does this have any justification?

I think i have most of it translated anyway

**Comment by gburton** [comment]
If you are 100% happy to provide translations for the most up-to-date fileset, using Github...then yes.  I am happy to provide a branch here for that purpose.  Let me know.

**Comment by boelle** [comment]
i have everything except the payment modules. Those i feel are limited to a very few select countries and they cant be used by danes anyway. Not sure if that disqualifies it?

**Comment by gburton** [comment]
I'd want it to be an exact copy of English (but in Danish)...

**Comment by boelle** [comment]
Then it will be disqualified as i will not waste my time on modules that cant be used by danes anyway

**Comment by boelle** [comment]
and the reason for they cant be used here is that none of them supports our national debit card "dankort", so even if i where to translate the "build in" modules like braintree and psigate etc it would be a waste  as they cant be used.

paypal is about the only one and even they do not support it but many customers have an paypal account. thou stores tend to abandon that too as the fees are to high compared to payment gateways like clearhaus that do not have a monthly fee, only a transaction fee that we by law can pass on to the customer, in effect making it free.
