### ISSUE TITLE
Paypal translation issues

### ISSUE THREAD

**Issue by Piernas** [gburton/Responsive-osCommerce#516]
I don't use the paypal app. When I tried to translate /hooks/admin/orders/tab.php found that I don't understand the "Capture payment" and "Void payment" concepts. @gburton can you explain me what do those terms exactly do so I can translate it?

**Comment by gburton** [comment]
Capture Payment:  Take money from Paypal
Void payment: I think this one says "order is cancelled, we dont need to take money from you"

https://library.oscommerce.com/Package&en&paypal&oscom23&order_administration
