### ISSUE TITLE
Modular index products?

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/Responsive-osCommerce#531]
I've a requirement to run manufacturer-specific promotions, videos, image gallery and so on.

I believe this could all be done with content modules with no core changes if there were a module group 'index products'.

If I code up the generic framework with maybe just one standard module for current core functionality
- manufacturer/category description

Would it be considered for core? Or are you trying to keep the volume of change as low as poss while other developments are ongoing?

**Comment by gburton** [comment]
I'm not quite sure what you're trying to do @BrockleyJohn - have something on the index page?  Could not you use a "index" content module?

**Comment by BrockleyJohn** [comment]
For this one I'm looking at adding stuff to this page: [http://bromleybr.co.uk/bsgit/index.php?manufacturers_id=2](http://bromleybr.co.uk/bsgit/index.php?manufacturers_id=2) but there has also been talk of doing something salesy here too [http://bromleybr.co.uk/bsgit/index.php?cPath=1_9](http://bromleybr.co.uk/bsgit/index.php?cPath=1_9)

Unless I'm missing something, core doesn't pick up modules at products level.

**Comment by gburton** [comment]
Ah I see. 
index_nested is for the categories (aka cPath) drill-down.
Maybe add a index_manufacturers call in index.php ?

**Comment by BrockleyJohn** [comment]
Yes, but index_nested doesn't go to the bottom - only categories that don't have products in (if I remember the test correctly).

Currently there's a single section of code that deals with the list of products in a category (whether filtered by manufacturer or not) and list of products for manufacturer (whether filtered by category or not).

Whether the query runs against category or manufacturer, it populates fields called something like $cat_name and $cat_description!

So it might be more straightforward to introduce modules for both at the same time and leave it up to the module to decide when it should appear.

**Comment by gburton** [comment]
Ah yeah I see.  index_products for if the depth is at "products".  Makes sense.
Let's see what you come up with...

**Comment by gburton** [comment]
@BrockleyJohn  did you manage to come up with anything ? 
Maybe we can add in a getContent call anyway, ready for modules? Thoughts?

**Comment by BrockleyJohn** [comment]
I had a quick play last week - enough to show that I'm unsatisfied with just adding the call. You can see the result here:
[manufacturer](http://bromleybr.co.uk/bsgit/index.php?manufacturers_id=2)
[category](http://bromleybr.co.uk/bsgit/index.php?cPath=1_9)
code is here: [branch](https://github.com/BrockleyJohn/Responsive-osCommerce/tree/modular_index_products_basic)

I'm intending, probably over the weekend, to look at modularising the existing category/manufacturer output which will be much more flexible for being able eg.  to add images higher up without using script to edit the dom.

**Comment by BrockleyJohn** [comment]
OK - here's another version. The above branch is still there and the corresponding index renamed to index_basic.php.
I like this one better. I have stuck to the current logic structure and modularised the output of category / manufacturer description (into a single common module), but not the page header or query. I have, however, done a little extra code-changing than strictly necessary by rationalising the variable names in the query and output to something less counter-intuitive. Links in the above comment now link to this version of index.php
code is here: [separate branch](https://github.com/BrockleyJohn/Responsive-osCommerce/tree/modular_index_products)
Clearly in this version the shopowner could have the image next to or above the description straightforwardly...

**Comment by gburton** [comment]
I like this, will leave open for future to-do
