### ISSUE TITLE
Update Paypal to v5

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#532]
http://addons.oscommerce.com/info/9184

**Comment by gburton** [comment]
The new Paypal App uses a crapload of older code than we have.  Eg:

mixture of http_*_vars and _*
mixture of dir_ws_* and harcoded
mixture of filename_* and hardcoded

and it looks like that isn't going to be changed anytime soon.  Potentially a problem.  Will think on this a while.

**Comment by BrockleyJohn** [comment]
compatibility module sticking plaster?

**Comment by gburton** [comment]
I dont like that compat module.  It's a poor solution.  We might as well just put the dumb filenames and other crap back into the Core.  

If the App remains as a mixture of old and new code ... it makes it useless for us.  

Potentially we could ... manually update each time a new version comes out.  
And remove the ability to update from within admin (just means removing the update-action).

That would solve things, but would mean we are slightly behind whenever an updated App comes out...

**Comment by Kymation** [comment]
I like my compatibility code a lot better. Well, of course I would. Still, it automates the constants and forever removes the need to update them manually. Should I put out my own competing Compatibility Addon. or just shut up and go away?

To actually answer Gary's question, that would seem to be the best answer. It means more work to keep your own Paypal App up to date, but it's the only solution that prevents recursion errors. Being slightly behind the main App is a much smaller problem.

**Comment by BrockleyJohn** [comment]
Clobbering the automatic update will stop the 'you broke my shop' whingeing. There are lots of users of the pp app so hopefully some of them will be willing to test.

**Comment by frankludriks** [comment]
I vote for manual update and being slightly behind.

**Comment by gburton** [comment]
The best option of all is to see if I can get the App updated to the more recent codebase (which would then be as good for the 2.3, but also good for this distro as well).  I will try.

If it's a no-go, then I think the best option is to put in a different "there's an update" message and rip out the automatic update action.

**Comment by MyBookShop** [comment]
I think it might be time to fork oscommerce plugins that work with the BS and Edge versions (as verified at a date) and ask maintaners to keep them up to date at **a new site**. Version Checker could be used maybe for BS and edge.

Then Paypal etc could just be an upload when its ready.

**Comment by gburton** [comment]
Paypal App now includes a compatibility layer for BS users.
