### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by MyBookShop** [gburton/Responsive-osCommerce#535]
I've just noticed that on Firefox and IE the pages render 4 products aside in Window and Ubuntu (all good).

In Safari and Firefox on my Ipad Air the front page renders like on an android or iPhone all products in one long line down, this also happens if more than one product is in a category.
In portrait mode it renders three products side by side then four. (No equal height mod installed which fixes the  3 then four but installed does not fix the portrait mode)

There is room on the Ipad display as the logo and search bar are side by side as normal.

This did not always happen and may have been broken recently?

I re-installed a clean copy of edge from the repo 2 days ago
and the clean copy also shows like this with no changes.

at a guess it may be bootstrap:-

http://getbootstrap.com/examples/grid/

**Comment by BrockleyJohn** [comment]
I would expect the tablet display in portrait to be the same as phones, but landscape to be the next one up.
From memory, the phone/tablet breakpoint is at 768pixels and the tablet/desktop breakpoint at 992px
You should be able to get exactly the same behaviour on the desktop by reducing the width of the browser window

**Comment by BrockleyJohn** [comment]
[http://whatsmy.browsersize.com/](http://whatsmy.browsersize.com/)

**Comment by BrockleyJohn** [comment]
@MyBookShop  Do you see the same on all pages that show a bunch of products?
- top level index (new products)
- within a category (new products in category)
- index products within a category
- new products page
- specials page

The first two have not been changed for ages, the last ones I changed last month and they may need tweaking. I don't have access to a recent Apple device and they behave as I expected on my ipad 2.

**Comment by gburton** [comment]
I missed this conversation.  What's the outcome @MyBookShop @BrockleyJohn

**Comment by MyBookShop** [comment]
I'm sorry.

I might have a dodgy I pad Air.

I will have access to another i-pad tomorrow.

The test was a clean/fresh install www.143books.com

It displays ok-ish in landscape but in portrait its like an I-phone when
displaying the New Products grid on the front page. The header and footer
etc are correct.

If you want to have a look and let me know.

Ta

**Comment by MyBookShop** [comment]
Yes it still displays badly on a new Ipad Air 2

The product grid is at fault.

It works better in landscape.
It did not do this a few revisions ago.

Ta.
Mark

**Comment by MyBookShop** [comment]
> I would expect the tablet display in portrait to be the same as phones,
> but landscape to be the next one up.
> From memory, the phone/tablet breakpoint is at 768pixels and the
> tablet/desktop breakpoint at 992px
> You should be able to get exactly the same behaviour on the desktop by
> reducing the width of the browser window
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gburton/Responsive-osCommerce/issues/535#issuecomment-283011898

Thankyou

The header and footer show correctly its the product grid that appears
broken, It did not used to it showed three at least from memory.

Ta

**Comment by BrockleyJohn** [comment]
OK - I got hold of a macbook earlier so I've seen what you're talking about and will have a look deeper into it. I think the products view within category has been like this since last summer but the new products on the front page just a few weeks.

**Comment by BrockleyJohn** [comment]
@MyBookShop please have a look at this test site and see if it's fixed: [http://bromleybr.co.uk/bsgit/](http://bromleybr.co.uk/bsgit/)

It's fixed on my ipad2 and through Browserstack right back to Safari 4 on Mountain Lion but it would be good to test it on your gear too.

**Comment by MyBookShop** [comment]
Yes that is what I'm getting too. Sadly. as @ 10.03.2017 still broken for this device.

**Comment by BrockleyJohn** [comment]
@MyBookShop - still broken in portrait but fixed in landscape?

**Comment by MyBookShop** [comment]
yes landscape appears better than on my site, just some unequal boxes. Yours appears fatter in boxes, mine are skinny. :)'

**Comment by BrockleyJohn** [comment]
@MyBookShop - think I have it beaten. You should now get the proper layout on my test site. Please test PR #538 on yours.

**Comment by MyBookShop** [comment]
I'm sorry to say that It did not appear to change on my Ipad2 Air.
Both in Safari and Mozilla.

Your site also looked the same, I uploaded your custom.css to my real site
@ www.143books.com.au as I'm using 143books.com for another purpose right
now.
If you would like to check, its a bit modded but the result is the same.


I really appreciate the help tho. I use the I pad to check my website's
externally available as I host myself.

Thankyou.

Mark

**Comment by BrockleyJohn** [comment]
@MyBookShop would you try this variation, please? [http://bromleybr.co.uk/bsdev/](http://bromleybr.co.uk/bsdev/)

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/pull/538

**Comment by MyBookShop** [comment]
Sorry have not had time to review this. yet. Will do so shortly.

Ta

**Comment by BrockleyJohn** [comment]
Please let me know how it is now for you.

Here's heads up, though. I'm afraid the Air2 seems to be a special case; I couldn't get everything working without breaking some other browser/device combinations, so the solution won't be perfect for you.

If needs be I can give you some styles to put into your user.css so your site favours ipad Air2 over Galaxy tab n (I forget now exactly which!)
