### ISSUE TITLE
USPS shipping module - hopelessly broken

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#536]
Rip it out ?

**Comment by Kymation** [comment]
I've been saying that for years. Unless you can guarantee a fast response to changes by updating the osCommerce release every time the USPS makes a change, which seems a bit unlikely.

**Comment by gburton** [comment]
@Kymation I know you have, and IIRC it's you who brought out a different module.  The last time I attempted to have a conversation with USPS, I ended up punching myself.  Their approach towards their API just sucks.

**Comment by Kymation** [comment]
I tried to create a better module that would not be as susceptible to their constant changes. They changed their API ("all" now means "some") so that my approach would not work. I could probably improve the current module, if I could ever get over my disgust for their broken API.

**Comment by gburton** [comment]
I'm thinking we just nuke this useless code.  
Thoughts?

**Comment by Kymation** [comment]
Remove it from core and leave the current Addon for anyone who wants to use it.

**Comment by gburton** [comment]
I agree @Kymation - will rip this out today.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/pull/544

**Comment by Kymation** [comment]
You should also remove /includes/classes/http_client.php. The USPS module was the only code using that class. Further, the httpClient class is outdated (does not support HTTP 1.1) and so cannot be safely used.

**Comment by gburton** [comment]
TY

https://github.com/gburton/Responsive-osCommerce/pull/545
