### ISSUE TITLE
Login does not show any text to indicate what is required 

### ISSUE THREAD

**Issue by LBManiac** [gburton/Responsive-osCommerce#539]
Hope this is the the right spot to post problems for this - just installed and love the new layout!

On the login page the customer is presesnted with 2 blank boxes, whilst most can figure this out is would be good to have Username + Password showing in the box which clears when they click to type it in?

I was able to replicate this on my own site and the demo page

![capture1](https://cloud.githubusercontent.com/assets/26495062/24077925/7efdae62-0c55-11e7-9a3a-73e07aa7335e.PNG)
![capture2](https://cloud.githubusercontent.com/assets/26495062/24077926/7efdcf00-0c55-11e7-9205-a4caf24c82dc.PNG)

**Comment by LBManiac** [comment]
I looked into this and just added placeholders for both fields in 
includes / modules / content / login / templates / login_form.php

`<div class="login-form <?php echo (MODULE_CONTENT_LOGIN_FORM_CONTENT_WIDTH == 'Half') ? 'col-sm-6' : 'col-sm-12'; ?>">
  <div class="panel panel-success">
    <div class="panel-body">
      <h2><?php echo MODULE_CONTENT_LOGIN_HEADING_RETURNING_CUSTOMER; ?></h2>

      <p class="alert alert-success"><?php echo MODULE_CONTENT_LOGIN_TEXT_RETURNING_CUSTOMER; ?></p>

      <?php echo tep_draw_form('login', tep_href_link('login.php', 'action=process', 'SSL'), 'post', '', true); ?>

        <div class="form-group">
          <?php echo tep_draw_input_field('email_address', NULL, 'autofocus="autofocus" required id="inputEmail" placeholder=**"Email address'** . ENTRY_EMAIL_ADDRESS_TEXT . '"', 'email'); ?>
        </div>

        <div class="form-group">
          <?php echo tep_draw_input_field('password', NULL, 'required aria-required="true" id="inputPassword" autocomplete="new-password" **placeholder="Password'** . ENTRY_PASSWORD_TEXT . '"', 'password'); ?>
        </div>

        <p class="text-right"><?php echo tep_draw_button(IMAGE_BUTTON_LOGIN, 'fa fa-sign-in', null, 'primary', NULL, 'btn-success btn-block'); ?></p>

      </form>
    </div>
  </div>

  <p><?php echo '<a class="btn btn-default" role="button" href="' . tep_href_link('password_forgotten.php', '', 'SSL') . '">' . MODULE_CONTENT_LOGIN_TEXT_PASSWORD_FORGOTTEN . '</a>'; ?></p>

</div>`

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/issues/413
https://github.com/gburton/Responsive-osCommerce/issues/401
and probably more.

**Comment by LBManiac** [comment]
Thanks, I'm a bit new to github (completely new) but I seen your guide on how to fork this to keep up to date 👍  -  would be happy to help with any testing as always keen to learn more and pick it up quickly
