### ISSUE TITLE
MySQL 5.7 Compatibility

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/Responsive-osCommerce#541]
This has come up a few times in the context of PHP7 and I have been working out why none of my testing has thrown any errors. I think it's worth documenting and deciding on separately.

Here's an example of a reported error:

> 3065 - Expression #1 of ORDER BY clause is not in SELECT list, references column 'web228_6.p.products_ordered' which is not in SELECT list; this is incompatible with DISTINCT
>
>select distinct p.products_id, pd.products_name from products p, products_description pd where p.products_status = '1' and p.products_ordered > 0 and p.products_id = pd.products_id and pd.language_id = '1' order by p.products_ordered desc, pd.products_name limit 10
>
>[TEP STOP]

thrown by includes/modules/boxes/bm_best_sellers.php

**What has changed in MySQL 5.7?**
- the server mode ONLY_FULL_GROUP_BY disables some MySQL extensions to standard SQL to force standard (and therefore portable) syntax. In MySQL 5.7.5 and higher, ONLY_FULL_GROUP_BY also affects handling of queries that use DISTINCT and ORDER BY (like the above)
- in MySQL 5.7.5 and higher the default server mode has ONLY_FULL_GROUP_BY enabled. Previously it was disabled by default.

**How big a problem is it?**
So far Manfred has reported errors in (and provided fixes for) 4 modules:
cm_i_new_products, cm_in_new_products, new_products and bm_best_sellers

**Who hits the problem?**
- Anyone setting themselves up a new server is quite likely to hit it (because it's a default setting). 
- People upgrading an existing server to MySQL5.7 might hit it (depending...).
- People on shared hosting are very unlikely to hit it, because it's very unlikely that ONLY_FULL_GROUP_BY will be enabled on shared hosting.

**What can be done about it?**
- the people running their own servers can change the server modes so that ONLY_FULL_GROUP_BY is disabled and the problem goes away
- anyone who doesn't have access to the server configuration can set the sql mode for their session (see code change to tep_db_connect in the link burt posted below) and the problem goes away
- the code could be fixed at some point in this version (or replaced in the next version of osc) but that will need testing in an environment that throws the error

**Comment by gburton** [comment]
http://forums.oscommerce.com/topic/410833-osc-234bs-edge-sql-code-and-install-script-issues/?p=1754242
