### ISSUE TITLE
tep_get_stock in Product Listing

### ISSUE THREAD

**Issue by BecRoM** [gburton/Responsive-osCommerce#542]
Hello,

If I active en configuration -> product listing -> Display Product Quantity...

Why in catalog/includes/modules/products_listing.php uses this:

    if ( (PRODUCT_LIST_QUANTITY > 0) && (tep_get_products_stock($listing['products_id']) > 0) ) {
      $extra_list_contents .= '<dt>' . TABLE_HEADING_QUANTITY . '</dt>';
      $extra_list_contents .= '<dd>' . tep_get_products_stock($listing['products_id']) . '</dd>';
    }

Instead of:

    if ( (PRODUCT_LIST_QUANTITY > 0) && ($listing['products_quantity'] > 0) ) {
      $extra_list_contents .= '<dt>' . TABLE_HEADING_QUANTITY . '</dt>';
      $extra_list_contents .= '<dd>' . $listing['products_quantity'] . '</dd>';
    }

I think, were are making innecesaries querys to get the products stock, when the stock is already in the query

Best regards :)

**Comment by gburton** [comment]
TY.

Could you test to make sure it works as expected.  Report back please.

**Comment by crazy-colorado** [comment]
This is good.

**Comment by BecRoM** [comment]
It works for me
