### ISSUE TITLE
Avoid hardcoded 'NONSSL'

### ISSUE THREAD

**Issue by katapofatico** [gburton/Responsive-osCommerce#549]
There are multiple occurrences with hardcoded 'NONSSL' as parameter of tep_href_link(). What do you think about replace them with dynamic variable $ request_type, so that they fit the configuration of each store. Otherwise, there may be multiple problems for SEO. Fortunately, in our store the migration to all-SSL implied defining the HTTP_SERVER variable with the https URL, therefore the problems was skipped. But the problem in the core persist

### Examples:
includes/functions/general.php:
```php
function tep_redirect($url) {
    if ( (strstr($url, "\n") != false) || (strstr($url, "\r") != false) ) { 
      tep_redirect(tep_href_link('index.php', '', 'NONSSL', false));
    }
[...]
}
```
includes/functions/sessions.php:
```php
  function tep_session_start() {
[...]
if ($sane_session_id == false) {
      tep_redirect(tep_href_link('index.php', '', 'NONSSL', false));
    }
[...]
}
```
includes/modules/header_tags/ht_canonical.php:
```php
    function execute() {
      global $PHP_SELF, $cPath, $oscTemplate, $category_depth;

      if (basename($PHP_SELF) == 'product_info.php') {
        $oscTemplate->addBlock('<link rel="canonical" href="' . tep_href_link('product_info.php', 'products_id=' . (int)$_GET['products_id'], 'NONSSL', false) . '" />' . PHP_EOL, $this->group);
```

What is your opinion? Are you agree? Do you have exceptions that need to be maintained?
If you are agree I can make the changes and push them.

**Comment by gburton** [comment]
TY.

Leave as they are.  When they are changed in v2.3.x of normal osCommerce, they will be changed here.
