### ISSUE TITLE
Reviews > CountryCode

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#559]
Googles new Shopping Feed system requires CountryCode;

Country of the reviewer. If available, this is the country the product was shipped to or where the service was rendered. Otherwise, use country the reviewer is in at the point of creating the review. The country code must be in ISO 3166-1 alpha-2 format.

As of now, the data is not easy to get as Reviews have no link to customer data (except for customer name) and no link to order data.

Solution: 
add customers_country to :table_reviews
save 2 letter ISO as part of products_write_review.php

Downside:
Does anyone see any?

Question:
How do we insert ISO code for already written (historical) reviews??

**Comment by crazy-colorado** [comment]
What about saving the countries_id?  This would allow for us to pull several fields for use in the future.  Knowing Google, they may change the requirement.

If you decide to go down that route, you could use the following sql to grab the delivery country from the order that customer placed for the item.

update reviews r
left join orders o on o.customers_id = r.customers_id
left join orders_products op on o.orders_id = op.orders_id and op.products_id = r.products_id
left join countries c on o.delivery_country = c.countries_name
set r.country_id = c.countries_id
where r.country_id is null;

After this, I would just recommend filling in with the store country.

**Comment by BrockleyJohn** [comment]
Which feed are we talking about here? I didn't think the Product Reviews aka Product Ratings feed had country, though I've not actually implemented it yet.
The GCR opt-in has country but that has nothing to do with osc reviews.

**Comment by BrockleyJohn** [comment]
Mandatory pros and cons seem a bigger hurdle for historical reviews than reviewer country!

**Comment by gburton** [comment]
https://developers.google.com/merchant-review-feeds/formats#countrycode

> Country of the reviewer. If available, this is the country the product was shipped to or where the service was rendered. Otherwise, use country the reviewer is in at the point of creating the review. The country code must be in ISO 3166-1 alpha-2 format.

**Comment by gburton** [comment]
And I had forgotten that the :table_reviews has customer_id !
We can actually grab the needed details quite easily.

I think it would still be useful to store the customers_country though.  I haven't thought deeply about whether to store the numeric ID of the country or the its ISO code.  Can we see a use for the numeric ID ?
