### ISSUE TITLE
Problem with newsletters.php

### ISSUE THREAD

**Issue by LordAzure** [gburton/Responsive-osCommerce#561]
When I click on Newsletters in admin I get the following.

Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in C:\Inetpub\vhosts\adulttoys4us.co.uk\httpdocs\VinceWebAdmin\newsletters.php on line 33

This is the line code:
`$allowed = array_map(function($v) {return basename($v, '.php');}, glob('includes/modules/newsletters/*.php'));`

Any suggestions? I have tried adding a random ) in various places, nothing works.

**Comment by BrockleyJohn** [comment]
Check the code before the line, maybe a statement is running into it. It should be like this:
`        if (isset($_POST['newsletter_id'])) $newsletter_id = tep_db_prepare_input($_POST['newsletter_id']);
        $newsletter_module = tep_db_prepare_input($_POST['module']);
        
        $allowed = array_map(function($v) {return basename($v, '.php');}, glob('includes/modules/newsletters/*.php'));
`

**Comment by BrockleyJohn** [comment]
wow the code formatting on here is terrible!

**Comment by LordAzure** [comment]
That's exactly right. is this code php version dependant?

**Comment by BrockleyJohn** [comment]
not really: 4.0.5+

**Comment by BrockleyJohn** [comment]
You should only be going into that line of code when you finish editing a locked newsletter, not when you just click on the menu option in admin. If that's happening there's something seriously wrong!

**Comment by LordAzure** [comment]
strange indeed

**Comment by LordAzure** [comment]
oh right,

**Comment by Kymation** [comment]
Anonymous functions require PHP 5.3 or higher.
