### ISSUE TITLE
div nesting issue with header.php/footer.php

### ISSUE THREAD

**Issue by surfalot** [gburton/Responsive-osCommerce#569]
header.php has an unmatched div:
`<div class="body-sans-header clearfix">`

I assume its match is the lone `</div>` footer.php

Problem arises since the code loads header.php in template_top.php AFTER the #bodyWrapper and .row divs:
```
    <div id="bodyWrapper" class="<?php echo BOOTSTRAP_CONTAINER; ?>">
    <div class="row">

      <?php require('includes/header.php'); ?>
```
Then later loads the footer.php in template_bottom.php, again, AFTER the closing  #bodyWrapper and .row divs:
```
    </div> <!-- row -->

  </div> <!-- bodyWrapper //-->

  <?php require('includes/footer.php'); ?>
```
Since header.php and footer.php have matched div tags, they need to be both inside or both outside the  #bodyWrapper and .row divs.

So, not sure what was intended. If the header and footer are supposed to be inside or outside.

**Comment by gburton** [comment]
Yeah, that looks like a bug...kinda.
Doesn't particularly matter I think as it just means one /div is used rather than the other.

It shouldn't be a problem to leave as is.

**Comment by surfalot** [comment]
OoohK. It was a problem for me, that is why I reported it. I went to add an additional set of divs to make the header and footer act differently and the whole layout barfed. So if you want to leave it and cause confusion for developers, your call.
