### ISSUE TITLE
Wont Update Paypal APP

### ISSUE THREAD

**Issue by drillsar** [gburton/Responsive-osCommerce#572]
Keeps saying update to version 5.018; I think supposed to be an update button.

**Comment by drillsar** [comment]
I think how it works supposed to be in SSL mode which I am. It seems to be a bug somewhere. Anyway shouldn't you update to version 5.018 anyway?

**Comment by gburton** [comment]
Why don't you update it, and then pump it back into this Core.

**Comment by drillsar** [comment]
@gburton No update available says version 5.018 available. However, in apps section only 5.010 is. Update button is also not visible.
