### ISSUE TITLE
account_notifications.php - Don't show text if box is not enabled.

### ISSUE THREAD

**Issue by frankludriks** [gburton/Responsive-osCommerce#577]
In account_notifications.php there is a line of text which will confuse customers.

If global notifications is not checked, and there are no product notifications for the customer, they are instructed "To add products to your product notification list, click on the notification link available on the detailed product information page."

This should be wrapped in a

if (MODULE_BOXES_PRODUCT_NOTIFICATIONS_STATUS == 'True') 

or changed.

**Comment by gburton** [comment]
Difficult one if I'm understanding the issue correctly...

If we wrap that block...customers can no longer access individual product notifications to turn them off (assuming shopowner for some reason for some reason had and then nuked the notifications box)...
