### ISSUE TITLE
Install chmod configure.php not working

### ISSUE THREAD

**Issue by drillsar** [gburton/Responsive-osCommerce#578]
in install/templates/install_page4

I see a couple of lines:
    @chmod($dir_fs_document_root . 'includes/configure.php', 0644);
    @chmod($dir_fs_document_root . 'admin/includes/configure.php', 0644);

I am guessing this supposed to change to 644 for both configure files, but it doesn't. Also I feel the configure files should be set at 444

Maybe also make it so all the files should be set at 644 like find . -type f chmod 644 {} \;
and directories 755 only certain dir need 777 like includes/work images I think

**Comment by gburton** [comment]
Invalid Issue.

Code mirrors (pretty much) the main osCommerce build.  
Obviously other than changes necessary to integrate Bootstrap.
