### ISSUE TITLE
have version checker check against this github 

### ISSUE THREAD

**Issue by boelle** [gburton/Responsive-osCommerce#582]
I noted that version has has gone up to 2.3.4.1

i wonder how i could have /admin/version_check.php use this git repro for the version check and not oscommerce.com

would it make sense? or is it just outright "stupid" ?

**Comment by gburton** [comment]
This github will soon be dead.  So no real point.

**Comment by boelle** [comment]
oh, what will happen?

**Comment by boelle** [comment]
got an explanation from John, in that a new repro will be created once the main oscommmerce reach a certain point

so yes no point in my idea

**Comment by gburton** [comment]
Once osCommerce releases v2.3.6, I'm going to be closing this Repo, and moving onto new projects.

**Comment by oitsuki** [comment]
Do you have a name about this new rep ?

**Comment by BrockleyJohn** [comment]
@oitsuki @boelle 
The other repo is already there, it's [https://github.com/osCommerce/oscommerce2](https://github.com/osCommerce/oscommerce2)

There is a branch (23 if I remember right) which is the development stream for osc 2.3

When that gets to the right stage for 234BS-based projects to migrate to the new core (maybe 2.3.6?), people who want to carry on controlling their code on github should create their own new project repo as a fork of osc2 and work in there.
