### ISSUE TITLE
Introduce HTML5 Custom Data Attributes

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#584]
Further Reading: http://html5doctor.com/html5-custom-data-attributes/

**Comment by BrockleyJohn** [comment]
I'm just getting into Facebook pixel and event tracking... it would be much better with price in the data attributes on Buy / Add to cart. Possibly other things when I'm further into the events.

PR when it's better understood?

**Comment by gburton** [comment]
@BrockleyJohn yes please.  we need to make far more use of HTML5 things.
