### ISSUE TITLE
CHARACTER SET and collation are lost in backup

### ISSUE THREAD

**Issue by Gergely** [gburton/Responsive-osCommerce#586]
Hi burt,

utf8 parts of the word lost all non latin_swedish characters in backups. There will be a big surprise after backup restoring.

**Comment by gburton** [comment]
TY

Please commit any fix(es)...

**Comment by Gergely** [comment]
https://github.com/Gergely/oscommerce2/commit/1a179112c0a9ebf08e40e117e268a71811e4a98f
