### ISSUE TITLE
PayPal standard return address

### ISSUE THREAD

**Issue by cupidare** [gburton/Responsive-osCommerce#590]
in 

includes/modules/payment/paypal_standard.php

in the 

function after_process()

it should mean 

tep_redirect(tep_href_link('checkout_success.php', '', 'SSL'));

not 

tep_redirect(tep_href_link('checkout_process.php', '', 'SSL'));

**Comment by gburton** [comment]
TY

https://github.com/gburton/Responsive-osCommerce/commit/311bc896d58d9c39a9f209c7fad3d2c4cdb5f837
