### ISSUE TITLE
Cart: remove product button not working with products with attributes 

### ISSUE THREAD

**Issue by veltsumatti** [gburton/Responsive-osCommerce#638]
This line  in includes/action/remove_product.php
$pid = (int)$_GET['products_id'];

strips the possible attributes

The value of $_GET['products_id'] is e.g. 26{3}8

The value of $pid will be 26.

Setting the amount to zero is currently the only way.

This is my fix:

        $products_id = $_GET['products_id'];
        //VMN2018$cart->remove($pid);
        $cart->remove($products_id);

**Comment by gburton** [comment]
TY

https://github.com/gburton/Responsive-osCommerce/commit/d447b73d1092aa4db42dde9c086119fdde02663f
