### ISSUE TITLE
Undefined variable in cm_pi_options_attributes.php

### ISSUE THREAD

**Issue by veltsumatti** [gburton/Responsive-osCommerce#639]
Notice:  Undefined variable: product_info in includes/modules/content/product_info/cm_pi_options_attributes.php on line 61

function execute:

the line:
      global $oscTemplate, $languages_id, $currencies;
should be:
      global $oscTemplate, $languages_id, $currencies, $product_info;

**Comment by gburton** [comment]
TY

https://github.com/gburton/Responsive-osCommerce/commit/ab7a31b014f4c9dca943d55bfe887e3dfc181594
