### ISSUE TITLE
Missing Content Module Manufacturers Name

### ISSUE THREAD

**Issue by tgort** [gburton/Responsive-osCommerce#640]
Just wondering if there's a missing content module to display the manufacturers name on the product info page: 
 /includes/modules/content/product_info list several modules: cm_pi_also_purchased.php cm_pi_gtin.php cm_pi_review_button.php cm_pi_buy_button.php cm_pi_model.php cm_pi_reviews.php cm_pi_date_available.php cm_pi_name.php cm_pi_description.php cm_pi_options_attributes.php cm_pi_gallery.php cm_pi_price.php. Similarly in the /product_info/tempates folder.
However, there doesn't seem to be a module to enable in the admin that would display the manufacturers name in product_info.

**Comment by gburton** [comment]
Hi.  It would need to be made as a Module, it does not presently exist.

**Comment by BrockleyJohn** [comment]
it's a box instead

**Comment by gburton** [comment]
Forgot about the box, thanks @BrockleyJohn
