### ISSUE TITLE
app top action executes should be static

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/Responsive-osCommerce#646]
Unless I'm missing something, all the execute methods in the actions classes should be
`public static function execute`

Adding product to basket from product info throws

> Deprecated: Non-static method osC_Actions_add_product::execute() should not be called statically in [catalog]/includes/classes/actions.php on line 20

**Comment by gburton** [comment]
Yep, chuck me a PR?

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/commit/a7614774421639bec037642fbf123dc443dc1a7f
