### ISSUE TITLE
category levels

### ISSUE THREAD

**Issue by puddlec** [gburton/Responsive-osCommerce#647]
3rd tier category appearing in 1st tier category on the main contents section, it does not do this in the category menu on the left-hand side

e.g.
if you put an extra category within CDROM drives, it will appear next to CDROM drives in the HARDWARE category, when it should only appear when in the CDROM category

![image](https://user-images.githubusercontent.com/11873636/39526796-c526444e-4e17-11e8-887b-13e82c85a7d9.png)

it did not use to do this. seems to have started when Class Call update on the 28th March was added, as the category listing modules worked fine before this

**Comment by gburton** [comment]
TY

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/commit/ac3b43031fa6553368a0b6dfde4945305e1ca2be
