### ISSUE TITLE
Schema links should be https

### ISSUE THREAD

**Issue by dbusr** [gburton/Responsive-osCommerce#654]
The following files have links like http://schema...
They should be https.

includes/modules/boxes/templates/best_sellers.php
includes/languages/english/modules/header_tags/ht_product_schema.php
includes/modules/header_tags/ht_product_schema.php
includes/modules/new_products.php
includes/modules/product_listing.php
includes/modules/content/index/templates/tpl_cm_i_new_products.php
includes/modules/content/index_nested/templates/tpl_cm_in_category_listing.php
includes/modules/content/index_nested/templates/tpl_cm_in_new_products.php
includes/modules/content/product_info/templates/tpl_cm_pi_also_purchased.php

**Comment by BrockleyJohn** [comment]
why?

**Comment by gburton** [comment]
http://schema.org/docs/faq.html#19

http is fine.
