### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dbusr** [gburton/Responsive-osCommerce#655]
I suggest that the following changes be made:

1 - In both application_top.php files, add the following after the error_reporting line:
 ini_set('display_errors','0'); 

The reason is that errors will display on some servers if that isn't present and that is considered a security issue since it provides hackers with details about the server.

2 - SSL Cert files for both authorize.net and paypal need to be updated.

3 - In template_top.php, change
<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
to
<script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>

4 - Make the shopping cart module core.

5 -  In languages/create_account_success.php priviledges should be privileges

6 - In languages/shopping_cart.php has "dont exist" and "immediate deliver in". Should be don't and immediate delivery.

7 - In create_account.php, change
     tep_redirect(tep_href_link('create_account_success.php', '', 'SSL'));

to the following to save a click on some checkouts

      if ($cart->count_contents() > 0) {
        tep_redirect(tep_href_link('checkout_shipping.php', '', 'SSL'));
      } else }
        tep_redirect(tep_href_link('index.php'));  
      }

**Comment by gburton** [comment]
1.  Not a bug
2.  Raise as Bug please
3.  Not a bug
4.  Feature Request - wont happen
5.  Not important
6.  Not important
7.  Feature Request - wont happen

Thanks.
