### ISSUE TITLE
Paypal app version

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/Responsive-osCommerce#656]
Seems to be back to v4.039 

@gburton have you backtracked and reverted it inadvertently?

I think I have it in a client repo if yours is gone.

**Comment by gburton** [comment]
I dont recall touching Paypal...

**Comment by BrockleyJohn** [comment]
I believe you updated the BS version of ppApp to 5.018 with php7 classes and superglobals in a commit on 28 Feb(ish) - or am I wrong?

I have it in the client's development branch but the master in that repo is a remote tracker of yours so it self-reverted... the commit in that stream is bbe6a1ce8a2bcb21e515ee74709568c2a9ad529d which ought to be the original sha

**Comment by BrockleyJohn** [comment]
no that commit is something else with a lot of update logs from one of my test sites - have I imagined the 5.018 update?

**Comment by gburton** [comment]
I don't recall doing anything recently with Paypal.  The history at https://github.com/gburton/Responsive-osCommerce/commits/master/includes/apps/paypal/version.txt just shows the initial commit...

**Comment by BrockleyJohn** [comment]
ok - cracking up then
