### ISSUE TITLE
Q: What could make drop down menu in navbar stop working?

### ISSUE THREAD

**Issue by boelle** [gburton/Responsive-osCommerce#665]
I have been catching up and i'm almost there

I have noted one thing thou and that is the account part in the right side of the navbar, the usual drop down menu that allows a login is not there... and if i click it i'm sent to root of shop but with a # added

https://test.pizzaløg.dk/

everything else seems to work, but what could break the nav bar account part?

EDIT: just checked and its the same for the drop down cart in navbar if there is an item in the cart

**Comment by BrockleyJohn** [comment]
I don't think you meant to raise this as a core issue! The menu loads fine for me. This behaviour occurs when the menu list doesn't properly get turned into a menu, usually when jquery doesn't load properly. Probably your browser has cached an incomplete load for the page - try a hard refresh.

**Comment by boelle** [comment]
nope, that is also why i put in the Q: first (ie question)

did not work with a hard refresh

**Comment by gburton** [comment]
http://forums.oscommerce.com

**Comment by BrockleyJohn** [comment]
Works for me in firefox and chrome

 

--

John  07834 809 883

SEwebsites

SE London/Kent
