### ISSUE TITLE
Unable to determine connection method on a link!

### ISSUE THREAD

**Issue by puddlec** [gburton/Responsive-osCommerce#669]
not sure if you seen this posted on the forum  (by someone else) or not but.

Error!
Unable to determine connection method on a link!
Known methods: NONSSL SSL

happen to me on the, on a number of pages
raiwa posted a fix for this below
https://forums.oscommerce.com/topic/412885-new-edge-install-unable-to-determine-connection-method-on-a-link/?tab=comments#comment-1769800

**Comment by gburton** [comment]
TY
https://github.com/gburton/Responsive-osCommerce/pull/664/commits/f7c6e9613ce9a190b39b58f43659fef2a9b1034f
