### ISSUE TITLE
Quantity from attributes not updating after finishing order

### ISSUE THREAD

**Issue by mando82** [gburton/Responsive-osCommerce#686]
I just installed a fresh copy, after testing with attributes I noticed the quantity isn't updated.

I'm adding some code to fix it, please check it.

checkout_process.php 

Line 202
Change
          $attributes_query = "select popt.products_options_name, poval.products_options_values_name, pa.options_values_price, pa.price_prefix, pad.products_attributes_maxdays, pad.products_attributes_maxcount , pad.products_attributes_filename 

To
          $attributes_query = "select popt.products_options_name, poval.products_options_values_name, pa.options_values_price, pa.price_prefix, pa.products_attributes_id, pa.options_quantity, pad.products_attributes_maxdays, pad.products_attributes_maxcount , pad.products_attributes_filename 

Line 215
Change:
          $attributes = tep_db_query("select popt.products_options_name, poval.products_options_values_name, pa.options_values_price, pa.price_prefix, from " . TABLE_PRODUCTS_OPTIONS . " popt, " . TABLE_PRODUCTS_OPTIONS_VALUES . " poval, " . TABLE_PRODUCTS_ATTRIBUTES . " pa where pa.products_id = '" . (int)$order->products[$i]['id'] . "' and pa.options_id = '" . (int)$order->products[$i]['attributes'][$j]['option_id'] . "' and pa.options_id = popt.products_options_id and pa.options_values_id = '" . (int)$order->products[$i]['attributes'][$j]['value_id'] . "' and pa.options_values_id = poval.products_options_values_id and popt.language_id = '" . (int)$languages_id . "' and poval.language_id = '" . (int)$languages_id . "'");

To:
          $attributes = tep_db_query("select popt.products_options_name, poval.products_options_values_name, pa.options_values_price, pa.price_prefix, pa.products_attributes_id, pa.options_quantity from " . TABLE_PRODUCTS_OPTIONS . " popt, " . TABLE_PRODUCTS_OPTIONS_VALUES . " poval, " . TABLE_PRODUCTS_ATTRIBUTES . " pa where pa.products_id = '" . (int)$order->products[$i]['id'] . "' and pa.options_id = '" . (int)$order->products[$i]['attributes'][$j]['option_id'] . "' and pa.options_id = popt.products_options_id and pa.options_values_id = '" . (int)$order->products[$i]['attributes'][$j]['value_id'] . "' and pa.options_values_id = poval.products_options_values_id and popt.language_id = '" . (int)$languages_id . "' and poval.language_id = '" . (int)$languages_id . "'");

Line 225 
ADD:
// begin quantity mod
$new_quantity = $attributes_values['options_quantity'] - $order->products[$i]['qty'];
tep_db_query("update " . TABLE_PRODUCTS_ATTRIBUTES . " set options_quantity = '" . (int)$new_quantity . "' where products_attributes_id = '" . $attributes_values['products_attributes_id'] . "'");
// end quantity mod

Some code was taken by another contrib (Can't remember which one now).
This should fix this issue, there is another issue from the shopping cart not checking attributes quantity and product info displaying 0 qty attributes.

**Comment by mando82** [comment]
To avoid showing 0 qty options in:
includes/modules/content/product_info/cm_pi_options_attributes.php

Replace Line 57: 
$products_options_query = tep_db_query("select pov.products_options_values_id, pov.products_options_values_name, pa.options_values_price, pa.price_prefix from products_attributes pa, products_options_values pov where pa.products_id = '" . (int)$_GET['products_id'] . "' and pa.options_id = '" . (int)$products_options_name['products_options_id'] . "' and pa.options_values_id = pov.products_options_values_id and pov.language_id = '" . (int)$languages_id . "'");

With:
          $products_options_query = tep_db_query("select pov.products_options_values_id, pov.products_options_values_name, pa.options_values_price, pa.price_prefix, pa.options_quantity from products_attributes pa, products_options_values pov where pa.products_id = '" . (int)$_GET['products_id'] . "' and pa.options_id = '" . (int)$products_options_name['products_options_id'] . "' and pa.options_values_id = pov.products_options_values_id and pa.options_quantity > '0' and pov.language_id = '" . (int)$languages_id . "'");

I think this should do it.

**Comment by gburton** [comment]
Attribute Quantity is not part of core code, this must be some addon you have used.
