### ISSUE TITLE
Installer does not work in 7.2

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#690]

**Comment by Piernas** [comment]
It works here under 7.2.6 - but looks messy on small devices.

**Comment by boelle** [comment]
not sure if related, but i have a site running with code dated back when code got status frozen

today the hosting company upgraded to php7.3 and when i do last confirm after picking payment method i get this error:

Fatal error: Uncaught Error: [] operator not supported for strings in /var/www/xn--pizzalg-v1a.dk/public_html/includes/modules/order_total/ot_rewardpoints.php:37 Stack trace: #0 /var/www/xn--pizzalg-v1a.dk/public_html/includes/classes/order_total.php(40): ot_rewardpoints->process() #1 /var/www/xn--pizzalg-v1a.dk/public_html/checkout_confirmation.php(122): order_total->process() #2 {main} thrown in /var/www/xn--pizzalg-v1a.dk/public_html/includes/modules/order_total/ot_rewardpoints.php on line 37

everything was fine yesterday. 
just a thought and not sure if there is any relation

**Comment by gburton** [comment]
TY.  MIght just be my testing environment.
