### ISSUE TITLE
Layout new products distorted on index and index-nested 

### ISSUE THREAD

**Issue by Rwkm** [gburton/Responsive-osCommerce#695]
Layout new products is distorted on index and index-nested

My custom hr images display very heigh and large.

The image tag in tpl_cm_i_card_products.php & tpl_cm_in_card_products.php is missing SMALL_IMAGE_WIDTH / SMALL_IMAGE_HEIGHT ?

**Comment by gburton** [comment]
Make sure your images are square (add blank background if necessary).
