### ISSUE TITLE
Can't edit checkout confirmation comment

### ISSUE THREAD

**Issue by mikepo** [gburton/Responsive-osCommerce#696]
During checkout confirmation, the comment box appears if not NULL, with an option to edit.

Clicking edit takes you back through the checkout process to change the comment, however the comment doesn't change unless you repeat the process ﻿or refresh the page.

I also noticed you can't remove/delete the comment.

I tried to modify the code, but the ﻿logic of passing the variables using $_POST I don't understand or I'm coding it wrong.

**Comment by gburton** [comment]
Do you know if this happens in the official build ?

**Comment by osc2nuke** [comment]
Not 100% sure , but exactly this problem was referenced in shops before the CE editions.
Did you @mikepo encounter this problem from an upgraded CE version?
Did you used some none BS converted module and adapted it ( or just overwrote a critical file)?
Did you took the LAST version and was able to reproduce the issue on that version without any additional modules?

**Comment by osc2nuke** [comment]
I have just a little hunt............
Do you use a module or a code that allow you to "Purchase without Account"?

**Comment by osc2nuke** [comment]
One more "old thought" i get is that it "might" be related to a specific payment-module.
( i faced this issue frequently, just long time ago and it comes down to a missing $var in the checkout-procedure).

**Comment by mikepo** [comment]
Gary, all I know this issue exists in the CE frozen version of May 2018.
I have the modular checkout version, so whether or not that introduces the problem I don't know.  I also have purchase without installed, but I know that this issue occurs when you are a guest or a regular account holder.
Regards
Mike

On 5 Jun 2019, at 17:24, gburton <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you know if this happens in the official build ?

**Comment by gburton** [comment]
Mike this is (more or less) a standard checkout from checkout_shipping onwards;  https://template.me.uk/outgoing/

Can you try it there?  I have followed your instructions and cannot (quite) recreate the error...

1.  add to cart
2.  create account or login
3.  add a comment in checkout_shipping
4.  progress to checkout_confirmation
5.  click edit (on the comment bit)

This takes me back to checkout_payment where I can edit the comment.

6.  press continue (to get back to checkout_confirmation

At this point I see my updated comment.

What I cannot do...is delete the comment, but that is (sort of) to be expected as we're editing it.   Come back to me in the next 7 days if you can...

In the meantime, I'll try to see why the comment cannot be changed to "" (nothing)...

**Comment by gburton** [comment]
```
if (!tep_session_is_registered('comments')) tep_session_register('comments');
  if (isset($_POST['comments']) && tep_not_null($_POST['comments'])) {
    $comments = tep_db_prepare_input($_POST['comments']);
  }
```

this piece of code checks the comment that is being submitted, it says:

IF "posted comments" EXISTS  
AND "posted comments" IS NOT NULL
UPDATE "comments" to match the "posted comments"

So, if the posted comments is EMPTY (eg when changing a comment from "something" to "" (nothing), the code will stop processing here:

if (isset($_POST['comments']) && tep_not_null($_POST['comments'])) {

and completely skip the update here:

$comments = tep_db_prepare_input($_POST['comments']);

So the value of $comments stays as whatever it was prior to the edit IF the edit was to totally remove the comment.  

Does all that make sense?  It's not quite a bug, but it's also not quite right to not be able to remove a comment.  I wonder if as a very quick fix;

```
if (!tep_session_is_registered('comments')) tep_session_register('comments');
  if (isset($_POST['comments']) && tep_not_null($_POST['comments'])) {
    $comments = tep_db_prepare_input($_POST['comments']);
  }
else {
  tep_session_unregister('comments');
}
```
may do it.  Can you find that code in your installation and try.

**Comment by mikepo** [comment]
Gary, will check this out and let you know, just give me a few days.
Mike

On 27 Jun 2019, at 16:59, gburton <notifications@github.com<mailto:notifications@github.com>> wrote:


if (!tep_session_is_registered('comments')) tep_session_register('comments');
  if (isset($_POST['comments']) && tep_not_null($_POST['comments'])) {
    $comments = tep_db_prepare_input($_POST['comments']);
  }


this piece of code checks the comment that is being submitted, it says:

IF "posted comments" EXISTS
AND "posted comments" IS NOT NULL
UPDATE "comments" to match the "posted comments"

So, if the posted comments is EMPTY (eg when changing a comment from "something" to "" (nothing), the code will stop processing here:

if (isset($_POST['comments']) && tep_not_null($_POST['comments'])) {

and completely skip the update here:

$comments = tep_db_prepare_input($_POST['comments']);

So the value of $comments stays as whatever it was prior to the edit IF the edit was to totally remove the comment.

Does all that make sense? It's not quite a bug, but it's also not quite right to not be able to remove a comment. I wonder if as a very quick fix;

if (!tep_session_is_registered('comments')) tep_session_register('comments');
  if (isset($_POST['comments']) && tep_not_null($_POST['comments'])) {
    $comments = tep_db_prepare_input($_POST['comments']);
  }
else {
  tep_session_unregister('comments');
}


may do it. Can you find that code in your installation and try.

**Comment by osc2nuke** [comment]
It is comming from your PWA/Guest account addon.
It is a known bug for almost 15 years.
The Chocolate Guy has the answer.
Forgot his name.

**Comment by osc2nuke** [comment]
It is comming from your PWA/Guest account addon.
It is a known bug for almost 15 years.
The Chocolate Guy has the answer.
Forgot his name.
Almost 100% sure it is the checkout process file involved.

**Comment by osc2nuke** [comment]
The only flaw osc has with guest is because of missing the (default) addresses.
Session storage could work this problem out.
It is a free tip.

**Comment by osc2nuke** [comment]
V3 allow checkout with only a customer registered via email and password.
No address need when checkout.
It go ask you.
( Keep in mind, it is not guest checkout, te user get An email with auto generated password and must conform)

**Comment by osc2nuke** [comment]
> Mike this is (more or less) a standard checkout from checkout_shipping onwards; https://template.me.uk/outgoing/
> 
> Can you try it there? I have followed your instructions and cannot (quite) recreate the error...
> 
> 1. add to cart
> 2. create account or login
> 3. add a comment in checkout_shipping
> 4. progress to checkout_confirmation
> 5. click edit (on the comment bit)
> 
> This takes me back to checkout_payment where I can edit the comment.
> 
> 1. press continue (to get back to checkout_confirmation
> 
> At this point I see my updated comment.
> 
> What I cannot do...is delete the comment, but that is (sort of) to be expected as we're editing it. Come back to me in the next 7 days if you can...
> 
> In the meantime, I'll try to see why the comment cannot be changed to "" (nothing)...

Here we go, Good Job!

**Comment by osc2nuke** [comment]
Gary, in your https://template.me.uk/outgoing/
If i logout before FIRST successful checkout  and want to checkout again, i get:

> Your E-Mail Address already exists in our records - please log in with the e-mail address or create an account with a different address.

If that happen let them redirect to ONLY a login page with option the recover password.
I think then it will be solid .

**Comment by gburton** [comment]
> If i logout before FIRST successful checkout and want to checkout again, i get:

Idea:  
logoff before checkout...immediately nuke the customer (allowing them to sign up again in the future, be that in 2 minutes or 2 days etc)

**Comment by osc2nuke** [comment]
I like that , but it freaks me out the increasing customer table id's.

I think it is not the 100% solid way.
But could work for the smaller shops.

**Comment by osc2nuke** [comment]
Just leave them in.
Tag them as guest.
Perhaps should get rid of Adress book limit.

**Comment by osc2nuke** [comment]
No, forgot that..
It Just aint right.
Guest orders should only be in orders tables.
I think the browser storage could be more usefull.

**Comment by osc2nuke** [comment]
Guest account was always a pain.
In PHP nuke we used 2 almost identical tables for users.
Cause of that we could either to let them pass, or if not wanted. Nuke them.
We could invent any system based on that before let them IN the real system. But that was old way of coding.

**Comment by osc2nuke** [comment]
Ask yourself the questions:
-who care who logs out?
-can i check Just via email of i exist in customer table?

The whole check if registered should be taken out.
It is noawady more regular to have no customers.
Guest is priority, customer is special.
Think of all the rules by law.
Opt-in/-out.

And much more.
Customers table not even need anymore.

Who change their email?
What is the chance i gonna hijack your email.
Beside, if i hijack your email i can gain also a new password from a specific shop.. no?

Just let it sink and give it a thought.

**Comment by osc2nuke** [comment]
Best example i can give of HOW it should work.

Order a meal via the takeaway websites.

You only het special treathment if registered 🧐

**Comment by osc2nuke** [comment]
Give me your thought on that. Pls.
Switch the thinking, and let's see with what possible problem can show up.
( OR have to deal with later).

Shopowners think customer.
Dev think : https://youtu.be/H4v7wddN-Wg

**Comment by osc2nuke** [comment]
Look at the complexity of the shopping cart class and specific on " returning' customer.

Useless checking.
One could store an abandoned cart in other ways.

Think of it.

**Comment by osc2nuke** [comment]
I played that YT video 5 times.
I go do it again, just couse it feels so correct and spot on.

**Comment by gburton** [comment]
> I like that , but it freaks me out the increasing customer table id's.

I dont worry about that, being the DB can go to the billions ;)

**Comment by gburton** [comment]
I do agree that the whole checkout urgently needs an overhaul.

**Comment by cdetdi** [comment]
“Quick fix” for this is to replace comment with just a space as it will
pass the condition and update.

**Comment by osc2nuke** [comment]
The whole point is it not hold previous comment

So i must replace:
Can you give me. noodles instead of rice.

Replace with a space and get angry customer?

**Comment by mikepo** [comment]
Hi Gary
Just checked this out.
If I change the code as you suggested, then when comments exist they are not shown on the confirmation page.

Don't forget I've got the modular checkout installed.
Mike

On 27 Jun 2019, at 17:12, Internet.mjp <internet.mjp@btconnect.com<mailto:internet.mjp@btconnect.com>> wrote:

Gary, will check this out and let you know, just give me a few days.
Mike

On 27 Jun 2019, at 16:59, gburton <notifications@github.com<mailto:notifications@github.com>> wrote:


if (!tep_session_is_registered('comments')) tep_session_register('comments');
  if (isset($_POST['comments']) && tep_not_null($_POST['comments'])) {
    $comments = tep_db_prepare_input($_POST['comments']);
  }


this piece of code checks the comment that is being submitted, it says:

IF "posted comments" EXISTS
AND "posted comments" IS NOT NULL
UPDATE "comments" to match the "posted comments"

So, if the posted comments is EMPTY (eg when changing a comment from "something" to "" (nothing), the code will stop processing here:

if (isset($_POST['comments']) && tep_not_null($_POST['comments'])) {

and completely skip the update here:

$comments = tep_db_prepare_input($_POST['comments']);

So the value of $comments stays as whatever it was prior to the edit IF the edit was to totally remove the comment.

Does all that make sense? It's not quite a bug, but it's also not quite right to not be able to remove a comment. I wonder if as a very quick fix;

if (!tep_session_is_registered('comments')) tep_session_register('comments');
  if (isset($_POST['comments']) && tep_not_null($_POST['comments'])) {
    $comments = tep_db_prepare_input($_POST['comments']);
  }
else {
  tep_session_unregister('comments');
}


may do it. Can you find that code in your installation and try.

**Comment by gburton** [comment]
OK, instead of

` tep_session_unregister('comments');`

try

`$comments = ''; `

**Comment by mikepo** [comment]
Sorry, Comments don't get passed on to the next page in the process if I use your suggestion below

On 1 Jul 2019, at 13:25, gburton <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, instead of

tep_session_unregister('comments');

try

$comments = '';

**Comment by gburton** [comment]
> Sorry, Comments don't get passed on to the next page in the process if I use your suggestion below

I guess take it into the Forum.
