### ISSUE TITLE
Module index cm_i_customer_greeting.php table name

### ISSUE THREAD

**Issue by thomasnordstrom** [gburton/Responsive-osCommerce#697]
A small friendly bug report in the following file:

/includes/modules/content/index/cm_i_customer_greeting.php

The table name in the install and remove methods is specified as:

:table_configuration

and it should be just

configuration

**Comment by gburton** [comment]
TY.

https://github.com/gburton/Responsive-osCommerce/commit/b5c84554b8981d806f491add393116e44ffe1fba
