### ISSUE TITLE
eval error in module if set_function is used and sql special characters

### ISSUE THREAD

**Issue by raiwa** [gburton/Responsive-osCommerce#699]
If "set_function" is used in a module and the configuration value contains sql special characters like  single quote (apostrophe), an eval error is thrown when the module is edited.

It is thrown in admin/modules_content.php line 294:

`          eval('$keys .= ' . $value['set_function'] . "'" .  $value['value'] . "', '" . $key . "');");`

adding "tep_db_input" solves it:

`          eval('$keys .= ' . $value['set_function'] . "'" .  tep_db_input($value['value']) . "', '" . $key . "');");`

Should this be considered to be fixed?

**Comment by gburton** [comment]
Have you tried tep_db_prepare_input ?

**Comment by raiwa** [comment]
Yes, it doesn't solve the error.

**Comment by raiwa** [comment]
The configuration entry I use is like follows:
`      include('includes/classes/language.php');
      $lng = new language;
      foreach($lng->catalog_languages as $key => $value) {
      	$key = strtoupper($value['directory']);
        tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Home Title " . $key . "', 'MODULE_CONTENT_HEADER_HOME_MESSAGE_HEADER_" . $key . "', 'Home Title', 'Home Message Title for " . $key . " language.', '6', '7', 'tep_cfg_module_textarea(', now())");
        tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Your Home Text " . $key . "', 'MODULE_CONTENT_HEADER_HOME_MESSAGE_TEXT_" . $key . "', 'Place any message you want to here, you can use it for any type of notice not just holidays', 'Home Message Text for " . $key . " language.', '6', '8', 'tep_cfg_module_textarea(', now())");
      }
`

And the textarea function is this:
  if(!function_exists('tep_cfg_module_textarea')) {
    function tep_cfg_module_textarea($text, $key = '') {
      $name = (($key) ? 'configuration[' . $key . ']' : 'configuration_value');
      return tep_draw_textarea_field($name, false, 35, 5, $text, 'style="font: inherit;"');
    }
  }
where I tried: 
`      return tep_draw_textarea_field($name, false, 35, 5, tep_db_prepare_input($text), 'style="font: inherit;"');
`
And several other possibilities to escape the sql special characters.
The only working solution I found is the modification in modules_content.php

The error I get when editing the content module is:
 syntax error, unexpected 't' (T_STRING), expecting ',' or ')' in C:\xampp_php_7_2_9\htdocs\xxxxxxxxxx/modules_content.php(297) : eval()'d code on line 1

The language loop and Key is not related, I checked without that.

**Comment by raiwa** [comment]
The problem can be easy reproduced using the standard function:
`tep_cfg_select_option(array(\'True\', \'False\')`
with the following values:
`tep_cfg_select_option(array(\'that's\', \'it's\')`

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/pull/716/commits/b561982001dde2fc1dd701414addcd2465a13bdf

**Comment by raiwa** [comment]
Sorry to come back late.
I found that a second modification is required:
in admin/modules_content.php line 302:
`$keys = substr($keys, 0, strrpos($keys, '<br /><br />'));`
should be modified to:
`      $keys = html_entity_decode(stripslashes(substr($keys, 0, strrpos($keys, '<br /><br />'))));
`
Otherwise escaping backslash will not be removed when editing a module and will produce duplicated backslashes when saved.
I applied this mod to my holyday message module and it works there flawless. Modified modules_content.php is included in the package:
https://apps.oscommerce.com/G3NiL&holiday-promotional-message-bs
