### ISSUE TITLE
[BUG?]  Information Links Block

### ISSUE THREAD

**Issue by boelle** [gburton/Responsive-osCommerce#708]
when i enable this module it throws an error on the shop side:

Warning
: Invalid argument supplied for foreach() in
/var/www/xn--pizzalg-v1a.dk/test/includes/modules/content/footer/cm_footer_information_links.php
on line
45

in the admin side i like the description: Adds Information Links Block to the Footer Area of your site

but where or how do i add the links themselfes?

**Comment by gburton** [comment]
In the relevant language file.

**Comment by boelle** [comment]
thanks, must have been blind

and thanks for unfreezeing :-D

**Comment by boelle** [comment]
still getting the error and i have this in my language file

<?php
/*
  $Id$
  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com
  Copyright (c) 2018 osCommerce
  Released under the GNU General Public License
*/
  define('MODULE_BOXES_INFORMATION_TITLE', 'Information');
  define('MODULE_BOXES_INFORMATION_DESCRIPTION', 'Show information page links');
  define('MODULE_BOXES_INFORMATION_BOX_TITLE', 'Information');
  
  const MODULE_BOXES_INFORMATION_BOX_DATA = array(
    'size.php' => 'Størrelse',
    'topping.php' => 'Fyld',
    'shipping.php' => 'Levering/Afhenting',
    'conditions.php' => 'Betingelser'
  );

**Comment by gburton** [comment]
Your PHP Version is ??

**Comment by boelle** [comment]
7.2

**Comment by gburton** [comment]
Did you read the readme ?

Minimum PHP Version
7.0
Maximum PHP Version
7.1.x

So, please ask for further support at the osCommerce Forum, as I am not working with 7.2 at the moment.

**Comment by boelle** [comment]
noep i did not, will just disable it for now.

its the only one

but let me know when/if there are a lot of repeated edits needed for upgrading to php 7.2
