### ISSUE TITLE
proposal: floating in product_info

### ISSUE THREAD

**Issue by cupidare** [gburton/Responsive-osCommerce#709]
I would suggest to change the classes in product_info to give it a BS3-behavior of floating. The benefit would be to have the large gallery on the one side and attributes, quantity, buy now on the right side without additional breaking by letting them float. This could be simply achieved by adding "d-block" to the product_info container and in each of the templates a "float-left". 

At least on larger displays this is a significant benefit and reestablishes the "function" of the container-width-selection of the child modules

**Comment by gburton** [comment]
Thank you for the suggestion.  I don't plan on changing the layout functionality at this point.
