### ISSUE TITLE
Fix Me

### ISSUE THREAD

**Issue by ruden** [gburton/Responsive-osCommerce#711]
https://github.com/gburton/Responsive-osCommerce/blob/c862e6c5c5432198f665b173837774a2aa1d3155/checkout_process.php#L215
https://github.com/gburton/Responsive-osCommerce/blob/c862e6c5c5432198f665b173837774a2aa1d3155/includes/modules/payment/inpay.php#L269
products_attributeS pa where
products_attribute^

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/pull/712/commits/a1dc666427a1a708b2e4f0e2358b3deb58144525
