### ISSUE TITLE
Manufacturer Class

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#721]
https://pastebin.com/AzAXX3nF

Quick and easy Manufacturer class. Any spot any potential problems ?

**Comment by ruden** [comment]
function getData($key = null) {
  return $this->_data[$key] ?? $this->_data;
}

**Comment by ruden** [comment]
@gburton 
Use for code https://gist.github.com/

**Comment by osc2nuke** [comment]
Curious if we can let it use:

`$manufacturer=` new objectInfo($this->_data);`

and always available as:
`$manufacturer->manufacturers_id`
