### ISSUE TITLE
Fix structured data

### ISSUE THREAD

**Issue by ruden** [gburton/Responsive-osCommerce#728]
Test https://search.google.com/structured-data/testing-tool

position - A value for the position field is required

**Comment by gburton** [comment]
Where might this problem be found ?

**Comment by ruden** [comment]
https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Ftemplate.me.uk%2Ffrozen2bs4%2F

**Comment by gburton** [comment]
That site is out of date.  But thanks anyway.
