### ISSUE TITLE
Question: Why deprecating database_tables and filenames

### ISSUE THREAD

**Issue by pflind** [gburton/Responsive-osCommerce#729]
Not an issue, but what is the benefit of deprecating `includes/database_tables.php` and `includes/filenames.php`?

Removing `database_tables.php ` is kind of a bad decision. Before it was removed there was an easy way of finding all references to a particular table name. Now when it's gone you can't even add table prefixes. I see only downsides.

**Comment by gburton** [comment]
To enable the concept of "no core code changes" more easily.
There are loads of posts in the osCommerce Forum about it, dating back years.
