### ISSUE TITLE
sub category not show up

### ISSUE THREAD

**Issue by osc2nuke** [gburton/Responsive-osCommerce#730]
Move a category above tier 2 ( so tier 3)
Let's choose hardware->graphic cards
Under "Graphic-Cards" at or move any of the other categories.
When i am inside of "Graphics Cards" 
The categories i moved or created or not showing up in the "index nested categories content module"
There is no follow link.
User not know.
Search engine not know.
(regardless if enabled or not the categories menu, no reason to have that categories-box to be enabled on the categories pages (right?)
)

**Comment by gburton** [comment]
Make sure that you do not have a mixture of products and categories at the same node.

IE, a category can contain ONLY products OR subcategories.

**Comment by osc2nuke** [comment]
No, if i am in HardWare i should (based on my settings) see new products for EACH underlying category.
Assume i moved one of the existing categories to "Graphic Cards" (or just made a new).
When i visit "Graphic Cards" i should be able to follow  somewhere inside the CM to follow the SUB category of "Graphic Cards" .
(ignoring the original categories menu, as i might not have it enabled when i call cPath, but might want it in the categories CM index_nested)

I try to point out flexibility, not who's right or wrong.

**Comment by gburton** [comment]
Get the products out of the category and you will see a sub-category list.
If that's no good, code up a new module to show the subcategories.

**Comment by osc2nuke** [comment]
No blame on you, but the category_class.php has serious problems.
(it is not even used to it's full in the whole osc code, not even go on on what it could do if extend that class).

**Comment by osc2nuke** [comment]
> If that's no good, code up a new module to show the subcategories.

I could,
Not forget i pointed out an issue, means i have no obligation to code a new module.
Making it is easy.
To get it accepted , that is another discussion.
So for the moment it is just an issue i point out.

**Comment by osc2nuke** [comment]
> Get the products out of the category and you will see a sub-category list.
> If that's no good, code up a new module to show the subcategories.

You know that this is not how it should work.
Common G.

**Comment by osc2nuke** [comment]
What i try to say is..........
By default should not LIMIT and make best product available.
If the end-user decide to minimize. That is up to him.
Atleast he cannot complain of how it was teach.
I am NOT looking for comments like:
If you know better: Do it.
I am NOT looking for that.
