### ISSUE TITLE
html_output

### ISSUE THREAD

**Issue by osc2nuke** [gburton/Responsive-osCommerce#731]
Get rid of html_ouput.
Has 0 use.
We only need session security on forms.

Thoughts. ( If you not understand why, feel free to ask me)

**Comment by gburton** [comment]
Feel free to elaborate.

**Comment by osc2nuke** [comment]
It is limiting in design and only proces default HTML.
If it would had build in options for example validation it would have good use.
Another reason is that the original code was made to fit jquery ui/960 grid. After we (you) had to change it to work with bootstrap.

I think it exist cause of php original was for and just kept it in.
(Programatic Hypertext Processor)
To generate HTML.

Give it a thought.

**Comment by gburton** [comment]
Fair.  But it is too much intertwined with all the other files to just remove it.
