### ISSUE TITLE
card-deck issue equal heights

### ISSUE THREAD

**Issue by osc2nuke** [gburton/Responsive-osCommerce#732]
I noticed the card-deck issue where the card-headers do not have an equal height.
Fix:
`<div class="card-header caption d-flex align-items-center justify-content-center h-100">`

Before fix:
![before-screenshot-tekshop247 local-2019 06 29-18-29-00](https://user-images.githubusercontent.com/5169035/60386912-218d6100-9a9c-11e9-8996-e35dc25ee9cc.png)

After:
![after-screenshot-tekshop247 local-2019 06 29-18-27-39](https://user-images.githubusercontent.com/5169035/60386914-281bd880-9a9c-11e9-9b57-57e34770810f.png)

Same Fix works for the body or footer.
How i implemented it:
Before:
![before-personal-screenshot-tekshop247 local-2019 06 29-18-35-06](https://user-images.githubusercontent.com/5169035/60386949-bd1ed180-9a9c-11e9-82a0-13a365aa6f44.png)
After:
![after-personal-screenshot-tekshop247 local-2019 06 29-18-33-39](https://user-images.githubusercontent.com/5169035/60386954-c7d96680-9a9c-11e9-8bb4-a33d27c55536.png)

**Comment by osc2nuke** [comment]
I must admit i not used the default stylesheet (user.css).
Not sure anymore if it is covered there.
However, this fix could reduce the user.css style-sheet.
I am in favor of 0 additional css and ONLY bootstrap.
If this fix is accepted, you could add one or **more** labels to it.
(So it can be found back).

**Comment by osc2nuke** [comment]
Just a little info and notice:

It is very cool to see how CSS managed to cover html>table.
It is very cool to see how bootstrap adopted this CSS knowledge.

**Comment by osc2nuke** [comment]
I like this FIX.... i need to go watch the ORDER!!! YT VIDEO now.

**Comment by osc2nuke** [comment]
possible Labels:
- Bootstrap
- Trick or Fix
- ?? (you choose lol)
- Equal Heights

**Comment by gburton** [comment]
Thanks.
Prefer to let shopowner make these micro-adjustments.
