### ISSUE TITLE
product info layout

### ISSUE THREAD

**Issue by osc2nuke** [gburton/Responsive-osCommerce#737]
detailed issue: https://forums.oscommerce.com/topic/492290-product-page-layout/

Solution:  do same as with the  navigation bar.
make a directory in modules: product_info_modules
Copy all product_info modules including templates.

make a new module cm_product_info.php in modules/content/product_info/

the template:
`
            <div class="row cm-product-info">    
                <?php
                if ($oscTemplate->hasBlocks('product_info_modules_top')) {
                    echo '<div class="col-sm-'. $content_width_top . '">';
                    echo    $oscTemplate->getBlocks('product_info_modules_top');
                    echo '</div>';
                }
                ?>      
                <?php
                if ($oscTemplate->hasBlocks('product_info_modules_left')) {
                    echo '<div class="col-sm-'. $content_width_left . '">';
                    echo '  <div class="row">';
                    echo    $oscTemplate->getBlocks('product_info_modules_left');
                    echo '  </div>';
                    echo '</div>';
                }
                if ($oscTemplate->hasBlocks('product_info_modules_right')) {
                    echo '<div class="col-sm-'. $content_width_right . '">';
                    echo '  <div class="row">';
                    echo    $oscTemplate->getBlocks('product_info_modules_right');
                    echo '  </div>';
                    echo '</div>';
                }    
                ?>
                <?php
                if ($oscTemplate->hasBlocks('product_info_modules_bottom')) {
                    echo '<div class="col-sm-'. $content_width_bottom . '">';
                    echo    $oscTemplate->getBlocks('product_info_modules_bottom');
                    echo '</div>';
                }
                ?>    
            </div>
`

Need some additional bootstrap class change in product_info.php

result:
![screenshot-tekshop247 local-2019 07 04-21-55-33](https://user-images.githubusercontent.com/5169035/60685983-8e429a00-9ea6-11e9-84c1-f669de449efe.png)

**Comment by osc2nuke** [comment]
of course for all product_info modules need to change them according how it is done for the navigation bar.
( i did it )

**Comment by gburton** [comment]
Introducing this brings as many problems as it solves.  I'm pretty happy with how the product_info is laid out - in the thread to which you link I show how to get the layout (by simply adding 1 line of .css code).  

If you can somehow come up with a parent module that allows unlimited layouts, (rather than limit to top-left-right-bottom) that would be awesome.

**Comment by osc2nuke** [comment]
I Read the post, but it not solve the problem.
The offered solution works just fine.
It is same like when you introduced the navbar.

I have btw a solution for a multi lay-out setup, but that would be for al

**Comment by osc2nuke** [comment]
The problem with lay-out consist in al files.
You did a good job.
I just do not like the fixed rules.
It is not your fault.
But forexample, i am unable to load specific "homepage" modules..
Where my index can contain so called sections.
This is because the fixed lay-out .
I personal think i should get flexebility, in either i want a module to be a container, a container-fluid a section, an aside.
There is nothing to blame on you.
But there are so many cool default plain HTML templates what seem to follow HTML/css rules.
Yet it is almost imposible to implement these to oscommerce without change core files.

That is the point i try to make.

**Comment by osc2nuke** [comment]
How much huge changes you adopted from someone else?

If it not comes from yourself, nothing ever comes.

Why you even try?
For who or what you are looking for?
Oscommerce is 2 decades behind.
Check your master who once in a while release top of notch code.

Not see anything evolve comming from that.

All changes you made, is only in your benifit.
I figure that.
You do not want progress.
You stall it on purpose.
You are not ligit.
Just a fool looking for fool customer.

But feeling in power.

**Comment by osc2nuke** [comment]
Must feel awesome.

**Comment by osc2nuke** [comment]
Next oscommerce Will be here:
https://oscommerce.ce.com

Let's see what you have to offer there with ligit people.

**Comment by osc2nuke** [comment]
Stop this bullshit.
Stop support this crap.

**Comment by osc2nuke** [comment]
It is never good enough for you.
Only when it is yours.

**Comment by osc2nuke** [comment]
So..
Let's stick to the subject.
Adopt the suggested lay-out for product info.
Why not?
Your gallery suggestion ONLY works when use the default gallery.

Seriously, do i really comprehend on that.

So... Osc users, you CANNOT CHANGE UNTILL TOLD.
Get the fuck off imposter.

**Comment by osc2nuke** [comment]
I cannot even blame Mr.Phill about flaming the release candidates.
He's right about that.

**Comment by osc2nuke** [comment]
Where is gergely email template system.
A HUGE progress for oscommerce.
Where is it?

What is the excuses?

**Comment by osc2nuke** [comment]
You not even adopt raiwa shopping cart modules.
Why?

**Comment by gburton** [comment]
Remember that even though you delete all your posts...everyone gets to read them.
