### ISSUE TITLE
Parse error: syntax error, unexpected '$heading' (T_VARIABLE)

### ISSUE THREAD

**Issue by puddlec** [gburton/Responsive-osCommerce#738]
Parse error: syntax error, unexpected '$heading' (T_VARIABLE)
C:\xampp72\htdocs\phoenix\admin\modules_content.php on line 304

$keys = html_en﻿tity_decode(stripslashes(substr($keys, 0, strrpos($keys, '<br /><br />'))));﻿﻿ 

      $heading[] = array('text' => '<strong>' . $mInfo->title . '</strong>');

had a quick look and an identical code exists on line 356

note
the code does not come out correctly when posting it here, so best go off the line numbers

php version 7.2.17
also tested on 7.1.30 - same error

**Comment by gburton** [comment]
TY

https://github.com/gburton/Responsive-osCommerce/commit/eb6e0a00ca6d56d9e622ebc2a13c9ba0f8b1694f
