### ISSUE TITLE
LF causing failure

### ISSUE THREAD

**Issue by dbusr** [gburton/Responsive-osCommerce#742]
In admin/modules_content at lines 302 and 356, there appears to be a LF that is causing the code to fail.  This is the error I see:

Parse error: syntax error, unexpected '$heading' (T_VARIABLE) in I:\Testing\Oscommerce_Responsive_Phoenix\admin\modules_content.php on line 304 

I use NotePad++, which has an option to replace all line feeds but even though it showed that it did it, the original code still failed. I tried attaching an image but in case it didn't take, I fixed this by replacing the line at 302 with the same except for the last character.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/commit/05b4d809ff2e87a9f46d76cd8699740c3d2c5389
