### ISSUE TITLE
PHP 7.3 Compatibility / Optimizations

### ISSUE THREAD

**Issue by haraldpdl** [gburton/Responsive-osCommerce#745]
Code checks still exist for PHP 4 and PHP 5 that can be removed. References to deprecated functions can also be removed. Long registered HTTP_*_VAR variables need to be replaced with superglobal variables.

(Pull Request incoming)

**Comment by gburton** [comment]
@haraldpdl thank you - I've pulled the changes into 1.0.0.4 branch, and all looks very well to me...

**Comment by gburton** [comment]
TY
https://github.com/gburton/Responsive-osCommerce/pull/746
