### ISSUE TITLE
Navbar Modules lose <ul> in Home Placement

### ISSUE THREAD

**Issue by rebelsheep** [gburton/Responsive-osCommerce#750]
Bug: Modules->Navbar Modules->Shopping Cart moved from Right, to Home...  Cart loses styling (also applies to Account, Currencies etc).

Fix?: This is because moving it to 'Home' the Cart is taken out of the encapsulating <.ul class="navbar-nav ml-auto">". The encapsulating <.ul> doesn't appear in 'Home' area. Not sure which file would need editing to fix it though.

**Comment by gburton** [comment]
Anything in HOME area does not need (and should not have) UL>LI etc.

https://getbootstrap.com/docs/4.3/components/navbar/#supported-content

**Comment by rebelsheep** [comment]
Why have the option to move Cart, Curriencies, Account etc to Home Placement then? <.li> elements shouldn't be without the <.ul>. For HTML to be correct and have Bootstrap conventions to be correct, then the navbar_modules (apart from Brand) shouldn't have the 'Home Placement' option.  ??

**Comment by gburton** [comment]
You would change the module appropriately in the TPL / language file.

**Comment by rebelsheep** [comment]
That would be considered a fix.
I recommend changing the navbar modules (except Brand) to have:

      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Content Placement Group', 'MODULE_NAVBAR_SHOPPING_CART_CONTENT_PLACEMENT', 'Right', 'Where should the module be loaded?  Lowest is loaded first, per Group.', '6', '1', 'tep_cfg_select_option(array(\'Left\', \'Right\'), ', now())");


'tep_cfg_select_option(array(\'Left\', \'Right\'), ', now())");

instead of:

'tep_cfg_select_option(array(\'Left\', \'Right\', \'Home\'), ', now())");

With the changes in the Phoenix release.
Home as an option doesn't make sense looking at Bootstrap and valid HTML.

**Comment by gburton** [comment]
No, the shopowner can choose to place an item in the Home area, and then amend the TPL file - it is what the TPL files are built for - custom solutions...

The only limiting factor is the Home area cannot support dropdown menus - so far as I recall - a limitation in Bootstrap.

If you want to get other peoples views (ie other than you and I) on it, make a discussion at the oscommerce forum.
