### ISSUE TITLE
GZIP no longer works

### ISSUE THREAD

**Issue by puddlec** [gburton/Responsive-osCommerce#752]
as per this thread
https://forums.oscommerce.com/topic/493725-gzip-compression-error-in-phoenix-1010/?tab=comments#comment-1791598

when turning on gzip
PHP Fatal error:  Uncaught Error: Call to undefined function tep_gzip_output()
﻿in /includes/application_b﻿otto﻿m.﻿p﻿﻿hp

missing line on application_top.﻿p﻿﻿hp
include("functions/gzip_compression.php");

**Comment by gburton** [comment]
@haraldpdl it looks like this got accidentally removed on the php7 updates.  Any advice?

**Comment by haraldpdl** [comment]
I'll get it fixed today.
