### ISSUE TITLE
stray blank spaces at the end of some template files

### ISSUE THREAD

**Issue by raiwa** [gburton/Responsive-osCommerce#756]
There are some stray blank spaces at the end after closing ?> in the following files:

includes/modules/content/index/templates/tpl_cm_i_title.php
includes/modules/content/index/templates/tpl_cm_i_upcoming_products.php
includes/modules/content/index_nested/templates/tpl_cm_in_title.php

Didn't check further, maybe a general cleanup would be good.

**Comment by gburton** [comment]
Sure, there should be a whole blank line after ?> in tpl files.

If a file has no ?> there should also be a whole blank line.

**Comment by raiwa** [comment]
Not blank line, blank spaces:

`
  3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
?>
     `

**Comment by gburton** [comment]
Yes, these don't matter in tpl files.  Thanks.
