### ISSUE TITLE
link to spanish lng packg.

### ISSUE THREAD

**Issue by raiwa** [gburton/Responsive-osCommerce#759]
Gary would you like to add a reference and link to the spanish language package to the readme?

**Comment by gburton** [comment]
Yes please, if it is "clean" and consists of only the needed files?

**Comment by raiwa** [comment]
I need to prepare a separate package with only the language files. I'll let you know tomorrow and give you the link.

**Comment by raiwa** [comment]
https://github.com/raiwa/OSCOM-CE-Phoenix-Spanish-language-idioma-espanol

**Comment by gburton** [comment]
Will push onto next point update.  TY.

**Comment by gburton** [comment]
1.0.1.3
