### ISSUE TITLE
Navbar Will Not Expand In Mobile Viewing - Mobile Phones - Other Small Devices

### ISSUE THREAD

**Issue by scro0303** [gburton/Responsive-osCommerce#760]
Responsive-osCommerce/includes/modules/content/navigation/cm_navbar.php

Recommended Change to Allow optimized viewing in small mobile devices such as a phone:

Change line #106:

      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Collapse', 'MODULE_CONTENT_NAVBAR_COLLAPSE', 'navbar-expand-sm', 'When should the Navbar Show? See https://getbootstrap.com/docs/4.3/components/navbar/#how-it-works', '6', '0', 'tep_cfg_select_option(array(\'navbar-expand-sm\', \'navbar-expand-md\', \'navbar-expand-lg\', \'navbar-expand-xl\'), ', now())");

To:

      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Collapse', 'MODULE_CONTENT_NAVBAR_COLLAPSE', 'navbar-expand', 'When should the Navbar Show? See https://getbootstrap.com/docs/4.3/components/navbar/#how-it-works', '6', '0', 'tep_cfg_select_option(array(\'navbar-expand\', \'navbar-expand-sm\', \'navbar-expand-md\', \'navbar-expand-lg\', \'navbar-expand-xl\'), ', now())");

I believe this very small change should be made to the core as "mobile first" should be considered if only as an option to users.

Attached are two photos showing: navbar-expand vs. navbar-expand-sm in a mobile viewing situation on a phone.

![20190801_213317000_iOS](https://user-images.githubusercontent.com/30706910/62329191-cc69b400-b47a-11e9-9c9b-8fcc4a194767.png)

![20190801_212922000_iOS](https://user-images.githubusercontent.com/30706910/62329189-cbd11d80-b47a-11e9-8ae3-9257c1e01311.png)

**Comment by gburton** [comment]
Turn on the hamburger navbar module.

**Comment by scro0303** [comment]
This update allows "Navbar Modules" in the "Content Placement Group" of "Left" and "Right" to be visible on the main Navbar "Home" in their positions of "Left" or "Right"...

The "Hamburger Menu" is great for items that you want to have nested within this Menu area...

This update would allow user to still have one or two of the very most important "Navbar Modules" items visible to their customers at all times.

I think this is a very valuable option for store owners.

With this update users would be allowed to choose what is best for their store.

This is just a small usability update to help store owners communicate better to their customers in a quick and easy manner.

Attached are pictures of the "Hamburger Menu" option and how items are nested out of the view of the customer unless the "Hamburger Menu" is clicked to reveal them.

![20190801_221847000_iOS](https://user-images.githubusercontent.com/30706910/62331468-a693dd80-b481-11e9-9625-cb26c520e378.png)
![20190801_221851000_iOS](https://user-images.githubusercontent.com/30706910/62331469-a693dd80-b481-11e9-8df8-fd744e3cfb46.png)

Lastly how it would look with this update if the user decides to change their settings to this update.

![20190801_212922000_iOS](https://user-images.githubusercontent.com/30706910/62331860-e9a28080-b482-11e9-9acf-6c521ad556a8.png)

**Comment by gburton** [comment]
What you're doing is making the navbar contents visible all the time even on XS (in other words it won't fold into a dropdown menu).   That's obviously not technically incorrect but is wrong in terms of UI for the vast majority of shops.   Do you see what I'm saying?

**Comment by gburton** [comment]
1.0.1.3
