### ISSUE TITLE
Form in Product Info should be optimised

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#89]
Needs to be made smaller, as it encompasses too much data.

**Comment by gburton** [comment]
Having said that, there is a need to be able to add modules inside the form, and outside the form.  Perhaps reducing the scope of the form, then adding another product_info CM call would be optimal ?

**Comment by BrockleyJohn** [comment]
Yes and correspondingly we need to be able to add modules in and outside the product microdata scope

**Comment by gburton** [comment]
What difference does having things in and out of the microdata?  Show me the light..

**Comment by BrockleyJohn** [comment]
Some things definitely want to be inside, like extra fields so you can microdata them if applicable. Thinking about it properly, it doesn't matter if stuff that's not about a product is inside as it won't be tagged.

**Comment by gburton** [comment]
Yes, that's my thought too.  If the "data" inside the microdata area does not need it, dont add it.  If it does do.  It shouldn't be an issue one way or another.  

On the other hand, the "inside" or "outside" form is an issue, in case the module maker needs to have a form inside a module.  The way the code currently is written would not allow this.

**Comment by frankludriks** [comment]
I propose osCommerce split the microdata from the form so that issue can be put aside http://forums.oscommerce.com/topic/410324-remove-product-schema-from-form-on-product-infophp/
